<?php
use App\Core\Csrf;
use App\Core\Env;
use App\Core\View;
$base=rtrim(Env::get('APP_URL',''),'/');
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ingresar — ERP Meli</title><link rel="stylesheet" href="<?= View::e(View::asset($base, 'app.css')) ?>"><style>
body{min-height:100vh;display:grid;place-items:center;background:#f4f7fb}.login-shell{width:min(960px,calc(100% - 32px));min-height:570px;display:grid;grid-template-columns:1fr 1fr;background:#fff;border:1px solid #dfe6ef;border-radius:14px;overflow:hidden;box-shadow:0 18px 60px rgba(11,23,57,.12)}.login-brand{background:#071a3b;color:#fff;padding:55px;display:flex;flex-direction:column;justify-content:space-between}.login-brand h1{font-size:38px;line-height:1.08;margin:0;letter-spacing:-.04em}.login-brand p{color:#adc0de;line-height:1.65;max-width:330px}.login-mark{width:46px;height:46px;background:#fff;color:#1769f5;border-radius:10px;display:grid;place-items:center;font-size:25px;font-weight:800}.login-safe{font-size:12px;color:#8fa7ca}.login-form{padding:70px 65px;display:flex;flex-direction:column;justify-content:center}.login-form h2{font-size:27px;margin:0}.login-form>p{color:#66738a;margin:8px 0 30px}.login-form .field{margin-bottom:17px}.login-form .btn{width:100%;margin-top:7px;height:44px}.login-foot{margin-top:26px;font-size:11px;color:#8390a4;text-align:center}@media(max-width:700px){.login-shell{grid-template-columns:1fr}.login-brand{display:none}.login-form{padding:45px 28px}}
</style></head><body><div class="login-shell"><section class="login-brand"><div><div class="login-mark">M</div><h1>ERP Meli</h1><p>Órdenes, pagos y cierres mensuales de todas tus cuentas en un solo lugar seguro.</p></div><div class="login-safe">Acceso interno · Operación de solo lectura</div></section><main class="login-form"><h2>Bienvenido</h2><p>Ingresa con tu cuenta interna.</p><?php if($error):?><div class="alert danger"><?= View::e($error) ?></div><?php endif;?><form action="<?= View::e($base) ?>/login" method="post"><input type="hidden" name="_token" value="<?= Csrf::token() ?>"><div class="field"><label for="email">Correo electrónico</label><input class="input" id="email" name="email" type="email" autocomplete="username" required autofocus></div><div class="field"><label for="password">Contraseña</label><input class="input" id="password" name="password" type="password" autocomplete="current-password" required></div><button class="btn primary" type="submit">Ingresar al ERP</button></form><div class="login-foot">Tus credenciales y tokens nunca se muestran en pantalla.</div></main></div></body></html>
