<?php
declare(strict_types=1);

$root=dirname(__DIR__);require $root.'/bootstrap.php';
use App\Core\Database;
use App\QueueCore\FreshOrdersDiscoveryHandler;
use App\QueueCore\FreshOrdersGateway;
use App\QueueCore\FreshOrdersProducer;
use App\QueueCore\QueueClaim;
use App\QueueCore\QueueCoreRepository;
use App\QueueCore\QueueExecutionContext;
use App\QueueCore\QueueHandler;
use App\QueueCore\QueueHandlerRegistry;
use App\QueueCore\QueueJob;
use App\QueueCore\QueueMetricsService;
use App\QueueCore\QueueResult;
use App\QueueCore\QueueRetryPolicy;
use App\QueueCore\QueueRunner;
use App\QueueCore\QueueRunRequest;
use App\QueueCore\CronV4Cli;
use App\QueueCore\HistoricalIngestionService;
use App\QueueCore\QueueCapabilityRegistry;
use App\QueueCore\QueueExecutionLeaseService;
use App\QueueCore\QueueCorePreRemoteBlockedException;
use App\Services\OAuthRefreshRequiredException;
use App\Services\CampaignItemState;
use App\QueueCore\ManualInputVersion;
use App\Services\ApiBudgetService;
use App\Services\ApiRhythmPolicyService;
use App\Services\AppSettingsService;
use App\Services\SchemaInspectorService;
use App\Core\Crypto;
use App\Services\MeliApiClient;
use App\Services\MeliHttpTransportInterface;

$dsn=getenv('QUEUE_CORE_TEST_DSN')?:'';$user=getenv('QUEUE_CORE_TEST_USER')?:'';$pass=getenv('QUEUE_CORE_TEST_PASS')?:'';
if($dsn===''){fwrite(STDERR,"QUEUE_CORE_TEST_DSN is required\n");exit(2);} $pdo=new PDO($dsn,$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$pdo->exec("SET time_zone='+00:00'");Database::setConnection($pdo);
$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['queue_core_dispatch_journal','queue_core_attempts','queue_core_events','queue_core_jobs','queue_core_producer_checkpoints','queue_core_scheduler_state','queue_core_account_fairness','queue_core_execution_leases','api_remote_permits','api_rhythm_states','api_rhythm_penalties','api_budget_windows','api_workload_estimates','app_settings','meli_tokens','meli_accounts'] as $t){$pdo->exec("DROP TABLE IF EXISTS `$t`");}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
$pdo->exec("CREATE TABLE meli_accounts (id BIGINT UNSIGNED NOT NULL PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,meli_user_id VARCHAR(80) NULL,account_name VARCHAR(100) NULL,status VARCHAR(40) NOT NULL) ENGINE=InnoDB");$pdo->exec("INSERT INTO meli_accounts VALUES (1,1,'101','A','conectado'),(2,1,'102','B','conectado'),(3,2,'201','C','conectado')");
$pdo->exec("CREATE TABLE meli_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL UNIQUE,access_token_encrypted MEDIUMTEXT NOT NULL,refresh_token_encrypted MEDIUMTEXT NULL,expires_at DATETIME NOT NULL,refresh_version BIGINT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE app_settings (setting_key VARCHAR(190) NOT NULL PRIMARY KEY,setting_value LONGTEXT NULL,is_encrypted TINYINT(1) NOT NULL DEFAULT 0,setting_group VARCHAR(80) NOT NULL DEFAULT 'general',updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_budget_windows (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,scope VARCHAR(40) NOT NULL,scope_key VARCHAR(255) NOT NULL,meli_account_id BIGINT UNSIGNED NULL,endpoint_path VARCHAR(255) NULL,job_type VARCHAR(80) NULL,window_started_at DATETIME NOT NULL,window_seconds INT UNSIGNED NOT NULL DEFAULT 900,request_limit INT UNSIGNED NOT NULL DEFAULT 0,request_count INT UNSIGNED NOT NULL DEFAULT 0,error_400_count INT UNSIGNED NOT NULL DEFAULT 0,error_401_count INT UNSIGNED NOT NULL DEFAULT 0,error_403_count INT UNSIGNED NOT NULL DEFAULT 0,error_429_count INT UNSIGNED NOT NULL DEFAULT 0,error_5xx_count INT UNSIGNED NOT NULL DEFAULT 0,last_request_at DATETIME NULL,cooldown_until DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_api_budget_window(scope_key,window_started_at,window_seconds)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_workload_estimates (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,module VARCHAR(80) NOT NULL,meli_account_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,estimated_calls INT UNSIGNED NOT NULL DEFAULT 0,allowed_calls INT UNSIGNED NOT NULL DEFAULT 0,result VARCHAR(40) NOT NULL DEFAULT 'allowed',safe_reason VARCHAR(500) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_rhythm_states (scope_key VARCHAR(64) NOT NULL PRIMARY KEY,generation BIGINT UNSIGNED NOT NULL DEFAULT 1,calls_in_block INT UNSIGNED NOT NULL DEFAULT 0,block_started_at DATETIME(3) NULL,next_allowed_at DATETIME(3) NULL,block_pause_until DATETIME(3) NULL,last_dispatched_at DATETIME(3) NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_remote_permits (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,permit_token CHAR(40) NOT NULL,owner_token CHAR(32) NOT NULL,generation BIGINT UNSIGNED NOT NULL,run_token VARCHAR(100) NULL,work_key VARCHAR(120) NULL,company_id BIGINT UNSIGNED NULL,meli_account_id BIGINT UNSIGNED NULL,endpoint_key VARCHAR(120) NOT NULL,job_type VARCHAR(80) NOT NULL,method VARCHAR(10) NOT NULL,status ENUM('reserved','dispatched','completed','released','expired') NOT NULL DEFAULT 'reserved',requested_interval_ms INT UNSIGNED NOT NULL,effective_interval_ms INT UNSIGNED NOT NULL,blocking_scope VARCHAR(80) NULL,http_status SMALLINT UNSIGNED NULL,created_at DATETIME(3) NOT NULL,dispatched_at DATETIME(3) NULL,completed_at DATETIME(3) NULL,released_at DATETIME(3) NULL,expires_at DATETIME(3) NOT NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE KEY uq_api_remote_permit_token(permit_token),KEY idx_api_remote_permit_active(status,expires_at)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_rhythm_penalties (scope_key VARCHAR(180) NOT NULL PRIMARY KEY,reduced_limit_per_minute SMALLINT UNSIGNED NOT NULL,blocked_until DATETIME(3) NULL,reduced_until DATETIME(3) NOT NULL,reason VARCHAR(80) NOT NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB");
$pdo->exec("INSERT INTO app_settings(setting_key,setting_value,is_encrypted,setting_group) VALUES ('api.budget.enabled','1',0,'api'),('api.rhythm.profile','maximum',0,'api_rhythm'),('api.rhythm.target_http_per_minute','40',0,'api_rhythm'),('api.rhythm.current_adaptive_limit','40',0,'api_rhythm'),('api.rhythm.minimum_interval_ms','1',0,'api_rhythm'),('api.rhythm.short_wait_ceiling_ms','0',0,'api_rhythm')");
$migrationFiles=['280_queue_core_cron_v4_phase_b1.sql','281_queue_core_reaudit1_fifo_fencing.sql'];foreach($migrationFiles as $migrationFile){$sql=file_get_contents($root.'/database/migrations/'.$migrationFile);if(!is_string($sql))throw new RuntimeException('migration missing');foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql)?:[] as $statement){$statement=trim($statement);$statement=preg_replace('/^--[^\n]*\n(?:--[^\n]*\n)*/','',$statement)??$statement;if($statement!=='')$pdo->exec($statement);}}
// Idempotency of the schema itself.
foreach($migrationFiles as $migrationFile){$sql=file_get_contents($root.'/database/migrations/'.$migrationFile);foreach(preg_split('/;\s*(?:\r?\n|$)/',(string)$sql)?:[] as $statement){$statement=trim($statement);$statement=preg_replace('/^--[^\n]*\n(?:--[^\n]*\n)*/','',$statement)??$statement;if($statement!=='')$pdo->exec($statement);}}

$results=[];$scenario=function(string $name,callable $test)use(&$results):void{try{$test();$results[$name]=true;echo "PASS $name\n";}catch(Throwable $e){$results[$name]=false;fwrite(STDERR,"FAIL $name ".$e->getMessage()."\n");}};$assert=function(bool $ok,string $message='assertion failed'):void{if(!$ok)throw new RuntimeException($message);};
$reset=function()use($pdo):void{$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['queue_core_dispatch_journal','queue_core_attempts','queue_core_events','queue_core_jobs','queue_core_producer_checkpoints','queue_core_execution_leases','meli_tokens','api_remote_permits','api_rhythm_states','api_rhythm_penalties','api_budget_windows','api_workload_estimates'] as $t)$pdo->exec("TRUNCATE TABLE `$t`");$pdo->exec('SET FOREIGN_KEY_CHECKS=1');$pdo->exec("UPDATE queue_core_scheduler_state SET cycle_position=0,generation=0 WHERE scheduler_key='default'");$pdo->exec("INSERT INTO queue_core_execution_leases(lease_key,generation) VALUES('global',0)");AppSettingsService::clearCache();SchemaInspectorService::clearCache();};
$parallel=function(string $mode):array{$start=(int)floor(microtime(true)*1000)+500;$procs=[];$outputs=[];for($i=0;$i<2;$i++){$pipes=[];$proc=proc_open([PHP_BINARY,__DIR__.'/fixtures/queue_core_race_worker.php',$mode,'worker-'.$i,(string)$start],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__));if(!is_resource($proc))throw new RuntimeException('parallel worker did not start');$procs[]=[$proc,$pipes];}foreach($procs as [$proc,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($proc);if($code!==0)throw new RuntimeException('parallel worker failed: '.$err);$outputs[]=json_decode((string)$out,true,32,JSON_THROW_ON_ERROR);}return $outputs;};
$job=function(int $account,string $lane,string $key,int $max=5,int $company=1):QueueJob{return new QueueJob($company,$account,'test_work','test_resource',$key,$lane,0,$key,'v1','test',null,['key'=>$key],[],$max);};
$request=function(string $worker,int $max=1,float $deadline=0,array $ids=[]):QueueRunRequest{return new QueueRunRequest('test',$worker,$max,$deadline>0?$deadline:microtime(true)+30,30,$ids);};

$scenario('fifo_order',function()use($reset,$assert,$job,$request,$pdo){$reset();$r=new QueueCoreRepository($pdo);$ids=[];foreach(['a','b','c'] as $key)$ids[]=$r->enqueue($job(1,'normal',$key));$seen=[];foreach(range(1,3) as $n){$c=$r->claimNext($request('fifo'.$n),['test_work']);$seen[]=$c?->id;$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::completed());}$assert($seen===$ids,'eligible jobs did not preserve FIFO');});
$scenario('fifo_no_priority_jump',function()use($reset,$assert,$request,$pdo){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue(new QueueJob(1,1,'test_work','r','a','historical_backfill',-100,'a','v1','test',null,[],[],3));$r->enqueue(new QueueJob(1,1,'test_work','r','b','fresh_orders',999,'b','v1','test',null,[],[],3));$assert($r->claimNext($request('fifo-priority'),['test_work'])?->id===$a,'lane or priority jumped FIFO');});
$scenario('blocked_head_does_not_block',function()use($reset,$assert,$job,$request,$pdo){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'normal','blocked'));$pdo->prepare("UPDATE queue_core_jobs SET state='waiting_oauth',wait_refresh_version=1 WHERE id=?")->execute([$a]);$b=$r->enqueue($job(1,'normal','ready'));$assert($r->claimNext($request('fifo-blocked'),['test_work'])?->id===$b);});
$scenario('fifo_concurrent_claim',function()use($pdo,$reset,$assert,$job,$parallel){$reset();$r=new QueueCoreRepository($pdo);$first=$r->enqueue($job(1,'normal','claim-a'));$second=$r->enqueue($job(2,'fresh_orders','claim-b'));$rows=$parallel('claim');$ids=array_values(array_filter(array_map(static fn(array $row):int=>(int)($row['id']??0),$rows)));sort($ids);$assert($ids===[$first,$second],'concurrent workers did not claim the first two FIFO jobs');});
$scenario('duplicate_producer_call',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'fresh_orders','same'));$b=$r->enqueue($job(1,'fresh_orders','same'));$assert($a===$b && (int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn()===1);});
$scenario('concurrent_producer_race',function()use($pdo,$reset,$assert,$parallel){$reset();$rows=$parallel('enqueue');$assert((int)$rows[0]['id']===(int)$rows[1]['id']&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE idempotency_key='parallel-producer'")->fetchColumn()===1);});
$scenario('duplicate_claim_race',function()use($pdo,$reset,$assert,$job,$parallel){$reset();(new QueueCoreRepository($pdo))->enqueue($job(1,'normal','claim'));$rows=$parallel('claim');$ids=array_values(array_filter(array_map(static fn(array $r):int=>(int)($r['id']??0),$rows)));$assert(count($ids)===1,'two concurrent workers claimed the same job');});
$scenario('lease_expiry_reclaim',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','lease'));$r->claimNext($request('old'),['test_work']);$pdo->exec("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=$id");$rec=$r->recoverStale();$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=$id");$new=$r->claimNext($request('new'),['test_work']);$assert($rec['retry_wait']===1&&$new?->leaseGeneration===2);});
$scenario('stale_generation_finalize_rejected',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','stale'));$old=$r->claimNext($request('old'),['test_work']);$oldAttempt=$r->beginAttempt($old,'test');$pdo->exec("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=$id");$r->recoverStale();$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=$id");$new=$r->claimNext($request('new'),['test_work']);$assert($new!==null&&!$r->finish($old,$oldAttempt,QueueResult::completed()));});
$scenario('retry_wait_eligibility',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','retry'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::retry('temporary',gmdate('Y-m-d H:i:s',time()+3600)));$assert($r->claimNext($request('x'),['test_work'])===null);$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3) WHERE id=$id");$assert($r->claimNext($request('y'),['test_work'])!==null);});
$scenario('retry_after_respected',function()use($assert,$root){$at=QueueRetryPolicy::nextAttemptAt(1,120);$then=new DateTimeImmutable($at,new DateTimeZone('UTC'));$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$delta=$then->getTimestamp()-$now->getTimestamp();$client=(string)file_get_contents($root.'/app/Services/MeliApiClient.php');$assert($delta>=119&&$delta<=121&&str_contains($client,'$status === 429 || $retryAfter !== null'));});
$scenario('dead_after_max_attempts',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','dead',1));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::retry('still_bad'));$assert(($r->job($id)['state']??'')==='dead');});
$scenario('bad_row_does_not_block',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$make=fn(string $key):QueueJob=>new QueueJob(1,1,'manual_exact','fixture',$key,'normal',0,$key,'v1','test',null,['key'=>$key],[],3);$bad=$r->enqueue($make('bad'));$good=$r->enqueue($make('good'));$registry=new QueueHandlerRegistry();$registry->register('manual_exact',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return ($j->payload['key']??'')==='bad'?QueueResult::dead('poison'):QueueResult::completed(1);}});$s=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','worker',2,microtime(true)+20));$assert(($r->job($bad)['state']??'')==='dead'&&($r->job($good)['state']??'')==='completed'&&$s['claimed']===2);});
$scenario('manual_cron_same_claim_path',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','shared'));$manual=$r->claimNext(new QueueRunRequest('manual','manual',1,microtime(true)+10,30,[$id]),['test_work']);$cron=$r->claimNext(new QueueRunRequest('cron_v4','cron',1,microtime(true)+10),['test_work']);$assert($manual!==null&&$cron===null);});
$scenario('automation_stop_zero_side_effects',function()use($pdo,$assert){$root=dirname(__DIR__);$marker=$root.'/PAUSE_ERP_AUTOMATION';file_put_contents($marker,'test');$before=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();try{$result=(new CronV4Cli())->run(['cron_v4.php','--runtime=5']);}finally{@unlink($marker);}$after=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$assert(($result['status']??'')==='SKIPPED_AUTOMATION_STOPPED'&&($result['side_effects']??-1)===0&&$before===$after);});
$scenario('ml_write_disabled_preserved',function()use($assert){putenv('ML_WRITE_ENABLED=false');$assert(getenv('ML_WRITE_ENABLED')==='false');});
$scenario('deadline_stops_claims',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$r->enqueue($job(1,'normal','deadline'));$registry=new QueueHandlerRegistry();$registry->register('test_work',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::completed();}});$s=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','w',10,microtime(true)-1));$assert($s['claimed']===0&&$s['reason']==='deadline');});
$scenario('uncertain_result_not_retried',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','uncertain'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$assert($r->dispatchStarted($c,$a,'GET','/orders/1'));$r->finish($c,$a,QueueResult::retry('transport'));$assert(($r->job($id)['state']??'')==='review');});
$scenario('producer_checkpoint_overlap',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$producer=new FreshOrdersProducer($pdo,$r,300,3600);$producer->scheduleDueAccounts();$row=$pdo->query("SELECT window_from,window_to,generation FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$from=is_array($row)?strtotime((string)$row['window_from'].' UTC'):false;$assert(is_array($row)&&$from!==false&&$from<=time()-3500);$gateway=new class implements FreshOrdersGateway{public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{return ['orders'=>[['id'=>'90001','date_created'=>$f,'input_version'=>'stable']], 'next_cursor'=>null,'has_more'=>false];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$r,$gateway));$runner=new QueueRunner($r,$registry);$runner->run(new QueueRunRequest('test','producer-one',1,microtime(true)+20,30,[],['fresh_orders_discovery'],1));$pdo->exec("UPDATE queue_core_producer_checkpoints SET next_due_at=UTC_TIMESTAMP(3) WHERE producer_key='fresh_orders' AND meli_account_id=1");$producer->scheduleDueAccounts();$runner->run(new QueueRunRequest('test','producer-two',1,microtime(true)+20,30,[],['fresh_orders_discovery'],1));$count=(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='order_exact' AND meli_account_id=1 AND resource_id='90001'")->fetchColumn();$assert($count===1,'overlap produced a duplicate order job');});
$scenario('producer_downtime_catchup',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pdo->exec("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,watermark_at,next_due_at,generation) VALUES('fresh_orders',1,1,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 2 DAY),UTC_TIMESTAMP(3),7)");(new FreshOrdersProducer($pdo,$r,300,3600))->scheduleDueAccounts();$raw=$pdo->query("SELECT payload_json FROM queue_core_jobs WHERE meli_account_id=1 AND work_type='fresh_orders_discovery' LIMIT 1")->fetchColumn();$payload=is_string($raw)?json_decode($raw,true):null;$from=is_array($payload)&&isset($payload['from'])?strtotime((string)$payload['from'].' UTC'):false;$assert($from!==false&&$from<=time()-2*86400-250,'downtime window was not materialized');});
$scenario('fresh_producer_continuous_without_reordering',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$old=$r->enqueue($job(1,'historical_backfill','old'));$producer=new FreshOrdersProducer($pdo,$r);$result=$producer->scheduleDueAccounts(1);$claim=$r->claimNext($request('w'),['test_work','fresh_orders_discovery']);$assert($result['enqueued']===1&&$claim?->id===$old,'fresh producer must run without jumping FIFO');});
$scenario('metrics_count_useful_progress_only',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'local','noop'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::completed(0));$first=(new QueueMetricsService($pdo))->snapshot();$id2=$r->enqueue($job(1,'local','useful'));$c2=$r->claimNext($request('w2'),['test_work']);$a2=$r->beginAttempt($c2,'test');$r->finish($c2,$a2,QueueResult::completed(1));$second=(new QueueMetricsService($pdo))->snapshot();$assert($first['resources_persisted']===0&&$second['resources_persisted']===1&&$second['last_useful_progress_at']!==null);});

$scenario('fifo_retry_reentry',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'normal','retry-a'));$b=$r->enqueue($job(1,'normal','retry-b'));$claim=$r->claimNext($request('retry-1'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$r->finish($claim,$attempt,QueueResult::retry('later',gmdate('Y-m-d H:i:s',time()+3600)));$assert($r->claimNext($request('retry-2'),['test_work'])?->id===$b);$pdo->prepare("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3) WHERE id=?")->execute([$a]);$claimB=$r->job($b);$pdo->prepare("UPDATE queue_core_jobs SET state='completed',lease_owner=NULL,lease_expires_at=NULL WHERE id=?")->execute([$b]);$assert($r->claimNext($request('retry-3'),['test_work'])?->id===$a);});
$scenario('historical_ingestion_bounded',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$jobs=(function(){for($i=0;$i<500;$i++)yield new QueueJob(1,1,'test_work','history',(string)$i,'historical_backfill',0,'hist-'.$i,'v1','fixture',null,[],[],3);})();$count=(new HistoricalIngestionService())->ingest($r,$jobs,500);$assert($count===HistoricalIngestionService::MAX_PER_CYCLE&&(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn()===$count);});
$scenario('transport_heartbeat_prevents_reclaim',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','heartbeat'));$claim=$r->claimNext($request('heartbeat-owner'),['test_work']);$r->beginAttempt($claim,'test');$pdo->prepare("UPDATE queue_core_jobs SET lease_expires_at=DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=?")->execute([$id]);$assert($r->heartbeat($claim,5));sleep(2);$recovered=$r->recoverStale();$assert(array_sum($recovered)===0&&($r->job($id)['state']??'')==='running','active heartbeat was reclaimed');});
$scenario('stale_heartbeat_rejected',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','heartbeat-stale'));$claim=$r->claimNext($request('heartbeat-old'),['test_work']);$r->beginAttempt($claim,'test');$pdo->prepare('UPDATE queue_core_jobs SET lease_generation=lease_generation+1 WHERE id=?')->execute([$id]);$assert(!$r->heartbeat($claim,30));});
$scenario('lost_transport_fence_becomes_review',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','lost-fence'));$claim=$r->claimNext($request('lost-owner'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$assert($r->physicalTransportStarted($claim,$attempt,'GET','/orders/1'));$pdo->prepare("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=?")->execute([$id]);$recovered=$r->recoverStale();$assert($recovered['review']===1&&($r->job($id)['state']??'')==='review'&&$r->claimNext($request('no-retry'),['test_work'])===null);});
$scenario('manual_global_lease_and_heartbeat',function()use($pdo,$reset,$assert){$reset();$service=new QueueExecutionLeaseService($pdo);$manual=$service->acquire('manual','manual-owner',5);$assert($manual!==null&&$service->heartbeat($manual)&&$service->acquire('manual','second-manual',5)===null);$pdo->exec("UPDATE queue_core_execution_leases SET expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE lease_key='global'");$cron=$service->acquire('cron_v4','cron-owner',5);$assert($cron!==null&&$cron->generation>$manual->generation);});
$scenario('cron_skips_manual_without_side_effects',function()use($pdo,$reset,$assert){$reset();putenv('CRON_V4_ENABLED=true');putenv('ML_WRITE_ENABLED=false');$service=new QueueExecutionLeaseService($pdo);$manual=$service->acquire('manual','manual-active',30);$before=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$result=(new CronV4Cli($pdo))->run(['cron_v4.php','--runtime=5']);$after=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$assert(($result['status']??'')==='SKIPPED_MANUAL_ACTIVE'&&($result['side_effects']??-1)===0&&($result['producer_calls']??-1)===0&&($result['stale_recovery']??-1)===0&&$before===$after);$service->release($manual);});
$scenario('manual_allowed_automation_cron_forbidden',function()use($pdo,$reset,$assert){$reset();$root=dirname(__DIR__);$automationMarker=$root.'/PAUSE_ERP_AUTOMATION';$apiMarker=$root.'/PAUSE_MELI_API';$savedApi=is_file($apiMarker)?file_get_contents($apiMarker):null;@unlink($apiMarker);putenv('APP_KEY=queue-core-fake-transport-key');$encrypted=Crypto::encrypt('fake-access-token');$pdo->prepare("INSERT INTO meli_tokens(meli_account_id,access_token_encrypted,expires_at,refresh_version) VALUES(?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 6 HOUR),1)")->execute([1,$encrypted]);$pdo->exec("INSERT INTO app_settings(setting_key,setting_value,is_encrypted,setting_group) VALUES('api.guard.enabled','0',0,'api') ON DUPLICATE KEY UPDATE setting_value='0',is_encrypted=0");AppSettingsService::clearCache();$r=new QueueCoreRepository($pdo);$manualId=$r->enqueue(new QueueJob(1,1,'manual_exact','fixture','1','normal',0,'manual-stop','v1','test',null,[],[],3));$cronId=$r->enqueue(new QueueJob(1,1,'order_exact','order','2','fresh_orders',0,'cron-stop','v1','test',null,[],[],3));$transport=new class implements MeliHttpTransportInterface{public int $calls=0;public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,(string)(parse_url($url,PHP_URL_PATH)?:'/'));App\QueueCore\QueueCoreDispatchFence::transportStarted($method,(string)(parse_url($url,PHP_URL_PATH)?:'/'));$this->calls++;return ['status'=>200,'body'=>['id'=>'123'],'headers'=>[],'curl_error'=>'','duration_ms'=>1,'wire_bytes'=>2,'decoded_bytes'=>2];}};$client=new MeliApiClient(1,$transport);$handler=new class($client) implements QueueHandler{public function __construct(private MeliApiClient $client){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{$this->client->get('/orders/123',[],['job_type'=>'manual_exact']);return QueueResult::completed(1,1);}};$registry=new QueueHandlerRegistry();$registry->register('manual_exact',$handler);$registry->register('order_exact',$handler);file_put_contents($automationMarker,'test');try{$manual=(new QueueRunner($r,$registry))->run(new QueueRunRequest('manual','manual-stop',1,microtime(true)+10,30,[$manualId],['manual_exact'],1));$cron=(new QueueRunner($r,$registry))->run(new QueueRunRequest('cron_v4','cron-stop',1,microtime(true)+10,30,[$cronId],['order_exact'],1));}finally{@unlink($automationMarker);if(is_string($savedApi))file_put_contents($apiMarker,$savedApi);else @unlink($apiMarker);}$assert($manual['completed']===1&&$transport->calls===1&&$cron['claimed']===0&&$cron['reason']==='automation_stopped','manual fake GET or Cron Automation Stop contract failed');});
$scenario('waiting_oauth_resumes_same_job',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO meli_tokens(meli_account_id,access_token_encrypted,expires_at,refresh_version) VALUES(1,'x',DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 HOUR),4)");$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'oauth-wait','v1','test',null,[],[],3));$registry=new QueueHandlerRegistry();$handler=new class implements QueueHandler{public int $calls=0;public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{$this->calls++;if($this->calls===1)throw new OAuthRefreshRequiredException($j->meliAccountId);return QueueResult::completed(1);}};$registry->register('fresh_orders_discovery',$handler);$runner=new QueueRunner($r,$registry);$first=$runner->run(new QueueRunRequest('test','oauth-one',1,microtime(true)+10));$assert(($r->job($id)['state']??'')==='waiting_oauth'&&$handler->calls===1);$busy=$runner->run(new QueueRunRequest('test','oauth-busy',1,microtime(true)+10));$assert($busy['claimed']===0);$pdo->exec("UPDATE meli_tokens SET refresh_version=5,expires_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 6 HOUR) WHERE meli_account_id=1");$second=$runner->run(new QueueRunRequest('test','oauth-two',1,microtime(true)+10));$assert($second['completed']===1&&$handler->calls===2&&($r->job($id)['state']??'')==='completed');});
$scenario('producer_due_before_limit',function()use($pdo,$reset,$assert){$reset();$insert=$pdo->prepare("INSERT INTO meli_accounts(id,company_id,meli_user_id,account_name,status) VALUES(?,?,?,?, 'conectado') ON DUPLICATE KEY UPDATE company_id=VALUES(company_id),meli_user_id=VALUES(meli_user_id),account_name=VALUES(account_name),status=VALUES(status)");for($i=1;$i<=30;$i++)$insert->execute([$i,(int)ceil($i/10),(string)(1000+$i),'A'.$i]);$cp=$pdo->prepare("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,next_due_at,generation) VALUES('fresh_orders',?,?,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL ? SECOND),0)");for($i=1;$i<=30;$i++)$cp->execute([(int)ceil($i/10),$i,$i===25?-1:3600]);$result=(new FreshOrdersProducer($pdo,new QueueCoreRepository($pdo)))->scheduleDueAccounts(1);$account=(int)$pdo->query("SELECT meli_account_id FROM queue_core_jobs WHERE work_type='fresh_orders_discovery' LIMIT 1")->fetchColumn();$assert($result['enqueued']===1&&$account===25);});
$scenario('manual_input_version_transition',function()use($pdo,$reset,$assert){$reset();$state=new CampaignItemState(true,false,true,true,'order_exact','Order','Ready',1,1,'ready');$v1=ManualInputVersion::derive(['source_id'=>'1','status'=>'pending'],$state);$same=ManualInputVersion::derive(['status'=>'pending','source_id'=>'1'],$state);$v2=ManualInputVersion::derive(['source_id'=>'1','status'=>'changed'],$state);$r=new QueueCoreRepository($pdo);$job=fn(string $version):QueueJob=>new QueueJob(1,1,'manual_exact','orders','1','normal',0,'manual:1',$version,'test',null,[],[],3);$a=$r->enqueue($job($v1));$b=$r->enqueue($job($same));$c=$r->enqueue($job($v2));$assert($v1===$same&&$v1!==$v2&&$a===$b&&$c!==$a&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='manual_exact'")->fetchColumn()===2);});
$scenario('capability_gate_rejects_uncertified',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'uncertified_remote','remote','1','normal',0,'uncertified','v1','test',null,[],[],3));$registry=new QueueHandlerRegistry();$registry->register('uncertified_remote',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::completed();}});$summary=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','capability',1,microtime(true)+10));$assert($summary['claimed']===0&&($r->job($id)['state']??'')==='pending');});
$scenario('pre_remote_fence_zero_physical',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','pre-remote'));$claim=$r->claimNext($request('pre-remote-owner'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$rhythm=new ApiRhythmPolicyService();$budget=new ApiBudgetService();$permit=$rhythm->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery','source_work_id'=>(string)$id]);$reservation=$budget->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery','source_work_id'=>(string)$id]);$assert($rhythm->dispatched($permit),'rhythm dispatch reservation failed');$pdo->prepare('UPDATE queue_core_jobs SET lease_generation=lease_generation+1 WHERE id=?')->execute([$id]);$denied=false;try{if(!$r->validateTransport($claim))throw new QueueCorePreRemoteBlockedException('denied');}catch(QueueCorePreRemoteBlockedException){$denied=true;$budget->releaseReservation($reservation);$rhythm->cancelBeforeTransport($permit);}$physical=(int)$pdo->query("SELECT physical_http_calls FROM queue_core_attempts WHERE id=$attempt")->fetchColumn();$budgetConsumed=(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn();$rhythmConsumed=(int)$pdo->query("SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states")->fetchColumn();$permitRow=$pdo->query("SELECT status,dispatched_at FROM api_remote_permits ORDER BY id DESC LIMIT 1")->fetch();$assert($denied&&$physical===0&&$budgetConsumed===0&&$rhythmConsumed===0&&($permitRow['status']??'')==='released'&&($permitRow['dispatched_at']??null)===null&&($r->job($id)['dispatch_state']??'')==='NOT_DISPATCHED','pre-remote rejection consumed a real budget/rhythm permit');});
$scenario('pre_remote_automation_race_refund',function()use($pdo,$reset,$assert){$reset();$marker=dirname(__DIR__).'/PAUSE_ERP_AUTOMATION';$rhythm=new ApiRhythmPolicyService();$budget=new ApiBudgetService();$permit=$rhythm->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);$reservation=$budget->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);try{file_put_contents($marker,'test');if((new App\Services\EmergencyControlService())->automationStopped()){throw new QueueCorePreRemoteBlockedException('automation race');}}catch(QueueCorePreRemoteBlockedException){$budget->releaseReservation($reservation);$rhythm->cancelBeforeTransport($permit);}finally{@unlink($marker);}$assert((int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states')->fetchColumn()===0&&(int)$pdo->query("SELECT COUNT(*) FROM api_remote_permits WHERE status<>'released'")->fetchColumn()===0,'Automation Stop race consumed a pre-HTTP permit');});
$scenario('pre_remote_owner_stale_refund',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','owner-stale'));$claim=$r->claimNext($request('owner-before'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$rhythm=new ApiRhythmPolicyService();$budget=new ApiBudgetService();$permit=$rhythm->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);$reservation=$budget->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);$assert($rhythm->dispatched($permit));$pdo->prepare("UPDATE queue_core_jobs SET lease_owner='owner-after' WHERE id=?")->execute([$id]);if(!$r->validateTransport($claim)){$budget->releaseReservation($reservation);$rhythm->cancelBeforeTransport($permit);}$assert((int)$pdo->query("SELECT physical_http_calls FROM queue_core_attempts WHERE id=$attempt")->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states')->fetchColumn()===0,'stale owner consumed a pre-HTTP permit');});
$scenario('metrics_windows_truthful',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'local','metrics-noop'));$claim=$r->claimNext($request('metrics'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$r->finish($claim,$attempt,QueueResult::completed(0));$reservedId=$r->enqueue($job(1,'normal','metrics-reserved'));$reserved=$r->claimNext($request('metrics-reserved'),['test_work']);$reservedAttempt=$r->beginAttempt($reserved,'test');$assert($reserved?->id===$reservedId&&$r->reserveTransport($reserved,$reservedAttempt));$snapshot=(new QueueMetricsService($pdo))->snapshot();$assert(isset($snapshot['window_60m'],$snapshot['current_depth'],$snapshot['cumulative'])&&$snapshot['window_60m']['dispatch_reserved']===1&&$snapshot['window_60m']['physical_http_started']===0&&$snapshot['window_60m']['completed_jobs']===1&&$snapshot['window_60m']['resources_persisted']===0&&$snapshot['last_resource_persisted_at']===null&&$snapshot['last_source_closed_at']!==null);});

$passed=count(array_filter($results));$total=count($results);echo "QUEUE_CORE_TESTS=$passed/$total\n";exit($passed===$total?0:1);
