<?php
declare(strict_types=1);

$root=dirname(__DIR__);require $root.'/bootstrap.php';
use App\Core\Database;
use App\QueueCore\FreshOrdersDiscoveryHandler;
use App\QueueCore\FreshOrdersGateway;
use App\QueueCore\FreshOrdersProducer;
use App\QueueCore\QueueClaim;
use App\QueueCore\QueueCoreRepository;
use App\QueueCore\QueueExecutionContext;
use App\QueueCore\QueueHandler;
use App\QueueCore\QueueHandlerRegistry;
use App\QueueCore\QueueJob;
use App\QueueCore\QueueMetricsService;
use App\QueueCore\QueueResult;
use App\QueueCore\QueueRetryPolicy;
use App\QueueCore\QueueRunner;
use App\QueueCore\QueueRunRequest;
use App\QueueCore\CronV4Cli;
use App\QueueCore\HistoricalIngestionService;
use App\QueueCore\QueueCapabilityRegistry;
use App\QueueCore\QueueExecutionLeaseService;
use App\QueueCore\QueueCorePreRemoteBlockedException;
use App\Services\OAuthRefreshRequiredException;
use App\Services\CampaignItemState;
use App\QueueCore\ManualInputVersion;
use App\QueueCore\ManualQueueLauncher;
use App\QueueCore\ManualExactHandler;
use App\QueueCore\ManualRemoteCapabilityRegistry;
use App\QueueCore\ManualSourceAuthorityService;
use App\QueueCore\OrderExactHandler;
use App\Services\OrderSyncService;
use App\Services\ApiBudgetService;
use App\Services\ApiRhythmPolicyService;
use App\Services\AppSettingsService;
use App\Services\SchemaInspectorService;
use App\Core\Crypto;
use App\Services\MeliApiClient;
use App\Services\MeliHttpTransportInterface;
use App\Services\ManualCampaignAdapterRegistry;
use App\Services\MeliOperationProfileRegistry;
use App\Services\CronDeadlineContext;

$dsn=getenv('QUEUE_CORE_TEST_DSN')?:'';$user=getenv('QUEUE_CORE_TEST_USER')?:'';$pass=getenv('QUEUE_CORE_TEST_PASS')?:'';
if($dsn===''){fwrite(STDERR,"QUEUE_CORE_TEST_DSN is required\n");exit(2);} $pdo=new PDO($dsn,$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$pdo->exec("SET time_zone='+00:00'");Database::setConnection($pdo);
$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['queue_core_health_snapshots','queue_core_readiness_receipts','queue_core_runs','queue_core_historical_reviews','queue_core_historical_receipts','queue_core_historical_checkpoints','queue_core_webhook_triggers','queue_core_capability_dependencies','queue_core_feature_flags','queue_core_pending_capabilities','queue_core_dispatch_journal','queue_core_attempts','queue_core_events','queue_core_jobs','queue_core_producer_checkpoints','queue_core_scheduler_state','queue_core_account_fairness','queue_core_execution_leases','api_remote_permits','api_rhythm_states','api_rhythm_penalties','api_budget_windows','api_workload_estimates','schema_migrations','app_settings','meli_tokens','cron_v3_work','system_work_queue','sale_financial_reconciliation_jobs','system_module_jobs','sync_sales_audit_jobs','sync_sales_audit_runs','sync_batch_chunks','order_resource_enrichment_jobs','meli_pack_orders','meli_order_items','meli_payments','meli_packs','meli_orders','meli_accounts'] as $t){$pdo->exec("DROP TABLE IF EXISTS `$t`");}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
$pdo->exec("CREATE TABLE meli_accounts (id BIGINT UNSIGNED NOT NULL PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,meli_user_id VARCHAR(80) NULL,account_name VARCHAR(100) NULL,status VARCHAR(40) NOT NULL) ENGINE=InnoDB");$pdo->exec("INSERT INTO meli_accounts VALUES (1,1,'101','A','conectado'),(2,1,'102','B','conectado'),(3,2,'201','C','conectado')");
$pdo->exec("CREATE TABLE meli_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL UNIQUE,access_token_encrypted MEDIUMTEXT NOT NULL,refresh_token_encrypted MEDIUMTEXT NULL,expires_at DATETIME NOT NULL,refresh_version BIGINT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE app_settings (setting_key VARCHAR(190) NOT NULL PRIMARY KEY,setting_value LONGTEXT NULL,is_encrypted TINYINT(1) NOT NULL DEFAULT 0,setting_group VARCHAR(80) NOT NULL DEFAULT 'general',updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE schema_migrations (version VARCHAR(191) NOT NULL PRIMARY KEY,applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE meli_orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,external_order_id VARCHAR(80) NOT NULL,external_pack_id VARCHAR(80) NULL,date_created DATETIME NULL,date_closed DATETIME NULL,status VARCHAR(40) NULL,status_detail VARCHAR(100) NULL,total_amount DECIMAL(18,2) NOT NULL DEFAULT 0,paid_amount DECIMAL(18,2) NOT NULL DEFAULT 0,currency_id VARCHAR(10) NULL,buyer_id VARCHAR(80) NULL,buyer_nickname VARCHAR(120) NULL,external_shipping_id VARCHAR(80) NULL,tags_json LONGTEXT NULL,raw_json LONGTEXT NULL,raw_path VARCHAR(255) NULL,synced_at DATETIME NULL,UNIQUE KEY uq_order_account_external(meli_account_id,external_order_id)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE meli_order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_order_id BIGINT UNSIGNED NOT NULL,meli_account_id BIGINT UNSIGNED NOT NULL,external_item_id VARCHAR(80) NOT NULL,external_variation_id VARCHAR(80) NULL,title VARCHAR(255) NULL,seller_sku VARCHAR(120) NULL,quantity DECIMAL(18,4) NOT NULL DEFAULT 0,unit_price DECIMAL(18,2) NOT NULL DEFAULT 0,full_unit_price DECIMAL(18,2) NULL,sale_fee DECIMAL(18,2) NOT NULL DEFAULT 0,listing_type_id VARCHAR(80) NULL,raw_json LONGTEXT NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE meli_packs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,external_pack_id VARCHAR(80) NOT NULL,external_shipment_id VARCHAR(80) NULL,buyer_json LONGTEXT NULL,status VARCHAR(40) NULL,raw_json LONGTEXT NULL,raw_path VARCHAR(255) NULL,synced_at DATETIME NULL,UNIQUE KEY uq_pack_account_external(meli_account_id,external_pack_id)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE meli_pack_orders (meli_pack_id BIGINT UNSIGNED NOT NULL,meli_order_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(meli_pack_id,meli_order_id)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE meli_payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,meli_order_id BIGINT UNSIGNED NOT NULL,external_payment_id VARCHAR(80) NOT NULL,status VARCHAR(40) NULL,status_detail VARCHAR(100) NULL,payment_method_id VARCHAR(80) NULL,payment_type VARCHAR(80) NULL,transaction_amount DECIMAL(18,2) NOT NULL DEFAULT 0,shipping_cost DECIMAL(18,2) NOT NULL DEFAULT 0,coupon_amount DECIMAL(18,2) NOT NULL DEFAULT 0,total_paid_amount DECIMAL(18,2) NOT NULL DEFAULT 0,marketplace_fee DECIMAL(18,2) NOT NULL DEFAULT 0,date_approved DATETIME NULL,raw_json LONGTEXT NULL,raw_path VARCHAR(255) NULL,synced_at DATETIME NULL,UNIQUE KEY uq_payment_account_external(meli_account_id,external_payment_id)) ENGINE=InnoDB");
foreach(['cron_v3_work','system_work_queue','sale_financial_reconciliation_jobs'] as $legacyTable)$pdo->exec("CREATE TABLE `$legacyTable` (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE sync_batch_chunks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,status VARCHAR(40) NOT NULL,sync_type VARCHAR(40) NOT NULL DEFAULT 'orders',date_from DATETIME NULL,date_to DATETIME NULL,cursor_offset INT NOT NULL DEFAULT 0,processed_count INT NOT NULL DEFAULT 0,estimated_total INT NOT NULL DEFAULT 0,next_run_at DATETIME NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE sync_sales_audit_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,status VARCHAR(40) NOT NULL DEFAULT 'running') ENGINE=InnoDB");
$pdo->exec("CREATE TABLE sync_sales_audit_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,status VARCHAR(40) NOT NULL,sync_sales_audit_run_id BIGINT UNSIGNED NOT NULL,next_offset INT NOT NULL DEFAULT 0,remote_reported_total INT NOT NULL DEFAULT 0,page_limit INT NOT NULL DEFAULT 20,next_run_at DATETIME NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE order_resource_enrichment_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,meli_order_id BIGINT UNSIGNED NOT NULL,resource_type VARCHAR(40) NOT NULL,external_resource_id VARCHAR(100) NOT NULL,status VARCHAR(40) NOT NULL DEFAULT 'pending',attempts INT NOT NULL DEFAULT 0,input_version VARCHAR(100) NULL,next_run_at DATETIME NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE system_module_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,meli_account_id BIGINT UNSIGNED NOT NULL,module_id VARCHAR(80) NOT NULL,job_type VARCHAR(80) NOT NULL,status VARCHAR(40) NOT NULL,stage VARCHAR(80) NULL,progress_current INT NOT NULL DEFAULT 0,progress_total INT NOT NULL DEFAULT 0,payload_json LONGTEXT NULL,checkpoint_json LONGTEXT NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_budget_windows (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,scope VARCHAR(40) NOT NULL,scope_key VARCHAR(255) NOT NULL,meli_account_id BIGINT UNSIGNED NULL,endpoint_path VARCHAR(255) NULL,job_type VARCHAR(80) NULL,window_started_at DATETIME NOT NULL,window_seconds INT UNSIGNED NOT NULL DEFAULT 900,request_limit INT UNSIGNED NOT NULL DEFAULT 0,request_count INT UNSIGNED NOT NULL DEFAULT 0,error_400_count INT UNSIGNED NOT NULL DEFAULT 0,error_401_count INT UNSIGNED NOT NULL DEFAULT 0,error_403_count INT UNSIGNED NOT NULL DEFAULT 0,error_429_count INT UNSIGNED NOT NULL DEFAULT 0,error_5xx_count INT UNSIGNED NOT NULL DEFAULT 0,last_request_at DATETIME NULL,cooldown_until DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_api_budget_window(scope_key,window_started_at,window_seconds)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_workload_estimates (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,module VARCHAR(80) NOT NULL,meli_account_id BIGINT UNSIGNED NULL,action VARCHAR(120) NOT NULL,estimated_calls INT UNSIGNED NOT NULL DEFAULT 0,allowed_calls INT UNSIGNED NOT NULL DEFAULT 0,result VARCHAR(40) NOT NULL DEFAULT 'allowed',safe_reason VARCHAR(500) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_rhythm_states (scope_key VARCHAR(64) NOT NULL PRIMARY KEY,generation BIGINT UNSIGNED NOT NULL DEFAULT 1,calls_in_block INT UNSIGNED NOT NULL DEFAULT 0,block_started_at DATETIME(3) NULL,next_allowed_at DATETIME(3) NULL,block_pause_until DATETIME(3) NULL,last_dispatched_at DATETIME(3) NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_remote_permits (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,permit_token CHAR(40) NOT NULL,owner_token CHAR(32) NOT NULL,generation BIGINT UNSIGNED NOT NULL,run_token VARCHAR(100) NULL,work_key VARCHAR(120) NULL,company_id BIGINT UNSIGNED NULL,meli_account_id BIGINT UNSIGNED NULL,endpoint_key VARCHAR(120) NOT NULL,job_type VARCHAR(80) NOT NULL,method VARCHAR(10) NOT NULL,status ENUM('reserved','dispatched','completed','released','expired') NOT NULL DEFAULT 'reserved',requested_interval_ms INT UNSIGNED NOT NULL,effective_interval_ms INT UNSIGNED NOT NULL,blocking_scope VARCHAR(80) NULL,http_status SMALLINT UNSIGNED NULL,created_at DATETIME(3) NOT NULL,dispatched_at DATETIME(3) NULL,completed_at DATETIME(3) NULL,released_at DATETIME(3) NULL,expires_at DATETIME(3) NOT NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),UNIQUE KEY uq_api_remote_permit_token(permit_token),KEY idx_api_remote_permit_active(status,expires_at)) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE api_rhythm_penalties (scope_key VARCHAR(180) NOT NULL PRIMARY KEY,reduced_limit_per_minute SMALLINT UNSIGNED NOT NULL,blocked_until DATETIME(3) NULL,reduced_until DATETIME(3) NOT NULL,reason VARCHAR(80) NOT NULL,updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)) ENGINE=InnoDB");
$pdo->exec("INSERT INTO app_settings(setting_key,setting_value,is_encrypted,setting_group) VALUES ('api.budget.enabled','1',0,'api'),('api.rhythm.profile','maximum',0,'api_rhythm'),('api.rhythm.target_http_per_minute','40',0,'api_rhythm'),('api.rhythm.current_adaptive_limit','40',0,'api_rhythm'),('api.rhythm.minimum_interval_ms','1',0,'api_rhythm'),('api.rhythm.short_wait_ceiling_ms','0',0,'api_rhythm')");
$migrationFiles=['280_queue_core_cron_v4_phase_b1.sql','281_queue_core_reaudit1_fifo_fencing.sql','282_queue_core_architecture_closeout_b1_2.sql','283_queue_engine_control_oauth_supervisor_b1_4.sql','284_queue_core_sales_pipeline_b2.sql','285_queue_core_webhook_ownership_b2.sql','286_queue_core_historical_deploy_b2.sql','287_queue_core_readiness_observability_b2.sql','288_queue_core_readiness_authority_b2_1.sql','289_queue_core_webhook_lifecycle_b2_1.sql','290_queue_core_sales_dependency_graph_b2_1.sql','291_queue_core_release_health_capacity_b2_1.sql'];foreach($migrationFiles as $migrationFile){$sql=file_get_contents($root.'/database/migrations/'.$migrationFile);if(!is_string($sql))throw new RuntimeException('migration missing');foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql)?:[] as $statement){$statement=trim($statement);$statement=preg_replace('/^--[^\n]*\n(?:--[^\n]*\n)*/','',$statement)??$statement;if($statement!=='')$pdo->exec($statement);}$record=$pdo->prepare('INSERT IGNORE INTO schema_migrations(version) VALUES (?)');$record->execute([$migrationFile]);}
// Idempotency of the schema itself.
foreach($migrationFiles as $migrationFile){$sql=file_get_contents($root.'/database/migrations/'.$migrationFile);foreach(preg_split('/;\s*(?:\r?\n|$)/',(string)$sql)?:[] as $statement){$statement=trim($statement);$statement=preg_replace('/^--[^\n]*\n(?:--[^\n]*\n)*/','',$statement)??$statement;if($statement!=='')$pdo->exec($statement);}}

$results=[];$scenario=function(string $name,callable $test)use(&$results):void{try{$test();$results[$name]=true;echo "PASS $name\n";}catch(Throwable $e){$results[$name]=false;fwrite(STDERR,"FAIL $name ".$e->getMessage()."\n");}};$assert=function(bool $ok,string $message='assertion failed'):void{if(!$ok)throw new RuntimeException($message);};
$reset=function()use($pdo):void{$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['queue_core_health_snapshots','queue_core_readiness_receipts','queue_core_runs','queue_core_historical_reviews','queue_core_historical_receipts','queue_core_historical_checkpoints','queue_core_webhook_triggers','queue_core_capability_dependencies','queue_core_pending_capabilities','queue_core_dispatch_journal','queue_core_attempts','queue_core_events','queue_core_jobs','queue_core_producer_checkpoints','queue_core_execution_leases','meli_tokens','cron_v3_work','system_work_queue','sale_financial_reconciliation_jobs','system_module_jobs','sync_sales_audit_jobs','sync_sales_audit_runs','sync_batch_chunks','order_resource_enrichment_jobs','meli_pack_orders','meli_order_items','meli_payments','meli_packs','meli_orders','api_remote_permits','api_rhythm_states','api_rhythm_penalties','api_budget_windows','api_workload_estimates'] as $t)$pdo->exec("TRUNCATE TABLE `$t`");$pdo->exec('SET FOREIGN_KEY_CHECKS=1');$pdo->exec("UPDATE queue_core_scheduler_state SET cycle_position=0,generation=0 WHERE scheduler_key='default'");$pdo->exec("UPDATE queue_core_feature_flags SET enabled=0,generation=0");$pdo->exec("INSERT INTO queue_core_execution_leases(lease_key,generation) VALUES('global',0)");AppSettingsService::clearCache();SchemaInspectorService::clearCache();};
$parallel=function(string $mode):array{$start=(int)floor(microtime(true)*1000)+500;$procs=[];$outputs=[];for($i=0;$i<2;$i++){$pipes=[];$proc=proc_open([PHP_BINARY,__DIR__.'/fixtures/queue_core_race_worker.php',$mode,'worker-'.$i,(string)$start],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__));if(!is_resource($proc))throw new RuntimeException('parallel worker did not start');$procs[]=[$proc,$pipes];}foreach($procs as [$proc,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($proc);if($code!==0)throw new RuntimeException('parallel worker failed: '.$err);$outputs[]=json_decode((string)$out,true,32,JSON_THROW_ON_ERROR);}return $outputs;};
$job=function(int $account,string $lane,string $key,int $max=5,int $company=1):QueueJob{return new QueueJob($company,$account,'test_work','test_resource',$key,$lane,0,$key,'v1','test',null,['key'=>$key],[],$max);};
$request=function(string $worker,int $max=1,float $deadline=0,array $ids=[]):QueueRunRequest{return new QueueRunRequest('test',$worker,$max,$deadline>0?$deadline:microtime(true)+30,30,$ids);};
$enableFakeApi=function(int $accountId=1)use($pdo):void{putenv('APP_KEY=queue-core-fake-transport-key');$encrypted=Crypto::encrypt('fake-access-token');$pdo->prepare("INSERT INTO meli_tokens(meli_account_id,access_token_encrypted,expires_at,refresh_version) VALUES(?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 6 HOUR),1) ON DUPLICATE KEY UPDATE access_token_encrypted=VALUES(access_token_encrypted),expires_at=VALUES(expires_at),refresh_version=VALUES(refresh_version)")->execute([$accountId,$encrypted]);$pdo->exec("INSERT INTO app_settings(setting_key,setting_value,is_encrypted,setting_group) VALUES('api.guard.enabled','0',0,'api') ON DUPLICATE KEY UPDATE setting_value='0',is_encrypted=0");AppSettingsService::clearCache();};
$fakeTransport=function(callable $response):MeliHttpTransportInterface{return new class($response) implements MeliHttpTransportInterface{public int $calls=0;public function __construct(private $response){}public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{$path=(string)(parse_url($url,PHP_URL_PATH)?:'/');App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,$path);App\QueueCore\QueueCoreDispatchFence::transportStarted($method,$path);$this->calls++;$body=($this->response)($method,$path,$data);return ['status'=>200,'body'=>is_array($body)?$body:[],'headers'=>[],'curl_error'=>'','duration_ms'=>1,'wire_bytes'=>2,'decoded_bytes'=>2];}};};

$scenario('fifo_order',function()use($reset,$assert,$job,$request,$pdo){$reset();$r=new QueueCoreRepository($pdo);$ids=[];foreach(['a','b','c'] as $key)$ids[]=$r->enqueue($job(1,'normal',$key));$seen=[];foreach(range(1,3) as $n){$c=$r->claimNext($request('fifo'.$n),['test_work']);$seen[]=$c?->id;$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::completed());}$assert($seen===$ids,'eligible jobs did not preserve FIFO');});
$scenario('fifo_no_priority_jump',function()use($reset,$assert,$request,$pdo){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue(new QueueJob(1,1,'test_work','r','a','historical_backfill',-100,'a','v1','test',null,[],[],3));$r->enqueue(new QueueJob(1,1,'test_work','r','b','fresh_orders',999,'b','v1','test',null,[],[],3));$assert($r->claimNext($request('fifo-priority'),['test_work'])?->id===$a,'lane or priority jumped FIFO');});
$scenario('blocked_head_does_not_block',function()use($reset,$assert,$job,$request,$pdo){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'normal','blocked'));$pdo->prepare("UPDATE queue_core_jobs SET state='waiting_oauth',wait_refresh_version=1 WHERE id=?")->execute([$a]);$b=$r->enqueue($job(1,'normal','ready'));$assert($r->claimNext($request('fifo-blocked'),['test_work'])?->id===$b);});
$scenario('fifo_concurrent_claim',function()use($pdo,$reset,$assert,$job,$parallel){$reset();$r=new QueueCoreRepository($pdo);$first=$r->enqueue($job(1,'normal','claim-a'));$second=$r->enqueue($job(2,'fresh_orders','claim-b'));$rows=$parallel('claim');$ids=array_values(array_filter(array_map(static fn(array $row):int=>(int)($row['id']??0),$rows)));sort($ids);$assert($ids===[$first,$second],'concurrent workers did not claim the first two FIFO jobs');});
$scenario('duplicate_producer_call',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'fresh_orders','same'));$b=$r->enqueue($job(1,'fresh_orders','same'));$assert($a===$b && (int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn()===1);});
$scenario('concurrent_producer_race',function()use($pdo,$reset,$assert,$parallel){$reset();$rows=$parallel('enqueue');$assert((int)$rows[0]['id']===(int)$rows[1]['id']&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE idempotency_key='parallel-producer'")->fetchColumn()===1);});
$scenario('duplicate_claim_race',function()use($pdo,$reset,$assert,$job,$parallel){$reset();(new QueueCoreRepository($pdo))->enqueue($job(1,'normal','claim'));$rows=$parallel('claim');$ids=array_values(array_filter(array_map(static fn(array $r):int=>(int)($r['id']??0),$rows)));$assert(count($ids)===1,'two concurrent workers claimed the same job');});
$scenario('lease_expiry_reclaim',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','lease'));$r->claimNext($request('old'),['test_work']);$pdo->exec("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=$id");$rec=$r->recoverStale();$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=$id");$new=$r->claimNext($request('new'),['test_work']);$assert($rec['retry_wait']===1&&$new?->leaseGeneration===2);});
$scenario('stale_generation_finalize_rejected',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','stale'));$old=$r->claimNext($request('old'),['test_work']);$oldAttempt=$r->beginAttempt($old,'test');$pdo->exec("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=$id");$r->recoverStale();$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=$id");$new=$r->claimNext($request('new'),['test_work']);$assert($new!==null&&!$r->finish($old,$oldAttempt,QueueResult::completed()));});
$scenario('retry_wait_eligibility',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','retry'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::retry('temporary',gmdate('Y-m-d H:i:s',time()+3600)));$assert($r->claimNext($request('x'),['test_work'])===null);$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3) WHERE id=$id");$assert($r->claimNext($request('y'),['test_work'])!==null);});
$scenario('retry_after_respected',function()use($assert,$root){$at=QueueRetryPolicy::nextAttemptAt(1,120);$then=new DateTimeImmutable($at,new DateTimeZone('UTC'));$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$delta=$then->getTimestamp()-$now->getTimestamp();$client=(string)file_get_contents($root.'/app/Services/MeliApiClient.php');$assert($delta>=119&&$delta<=121&&str_contains($client,'$status === 429 || $retryAfter !== null'));});
$scenario('dead_after_max_attempts',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','dead',1));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::retry('still_bad'));$assert(($r->job($id)['state']??'')==='dead');});
$scenario('automatic_wait_does_not_consume_failure_budget',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','policy-wait',1));for($i=0;$i<100;$i++){$claim=$r->claimNext($request('policy-'.$i),['test_work']);$assert($claim!==null,'automatic wait was not claimable at iteration '.$i);$attempt=$r->beginAttempt($claim,'test');$assert($r->finish($claim,$attempt,QueueResult::automaticWait('policy_deferred',gmdate('Y-m-d H:i:s'))));$row=$r->job($id);$assert(($row['state']??'')==='retry_wait'&&(int)($row['attempt_count']??-1)===0,'automatic wait consumed a failure attempt');}$assert((int)$pdo->query("SELECT COUNT(*) FROM queue_core_attempts WHERE job_id=$id")->fetchColumn()===100,'policy wait attempt history was not preserved');});
$scenario('remote_429_counts_as_real_failure',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'order_exact','order','429','normal',0,'remote-429','v1','test',null,['order_id'=>'429'],[],2,null,'operational'));$registry=new QueueHandlerRegistry();$registry->register('order_exact',new class($r) implements QueueHandler{public function __construct(private QueueCoreRepository $repository){}public function handle(QueueClaim $job,QueueExecutionContext $context):QueueResult{$this->repository->physicalTransportStarted($job,$context->attemptId,'GET','/orders/429');$this->repository->responseKnown($job,$context->attemptId,429);throw new App\Services\ApiRhythmDeferredException('remote 429',gmdate('Y-m-d H:i:s'),'retry_after',true);}});$runner=new QueueRunner($r,$registry);for($i=0;$i<2;$i++){$runner->run(new QueueRunRequest('test','remote-429-'.$i,1,microtime(true)+10,30,[],['order_exact'],1,null,'operational',$id));}$row=$r->job($id);$assert(($row['state']??'')==='dead'&&(int)($row['attempt_count']??0)===2&&(int)($row['last_http_status']??0)===429,'known remote 429 did not consume the real failure budget '.json_encode(['state'=>$row['state']??null,'attempts'=>$row['attempt_count']??null,'status'=>$row['last_http_status']??null]));$pdo->prepare('UPDATE queue_core_jobs SET updated_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 61 SECOND) WHERE id=?')->execute([$id]);$assert($r->reviveExhaustedTransient($id,'order_exact','v1',1,1)&&($r->job($id)['state']??'')==='pending','dead transient 429 was not revivable under the same FIFO identity');});
$scenario('handler_deadlines_never_exhaust_failure_budget',function()use($pdo,$reset,$assert){
    $cases=[];
    $cases['fresh_orders_discovery']=static function(QueueCoreRepository $r)use($pdo):QueueHandler{
        $gateway=new class implements FreshOrdersGateway{public int $calls=0;public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{$this->calls++;throw new RuntimeException('deadline handler called gateway');}};
        return new class(new FreshOrdersDiscoveryHandler($pdo,$r,$gateway)) implements QueueHandler{public function __construct(private QueueHandler $inner){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return $this->inner->handle($j,new QueueExecutionContext($c->attemptId,microtime(true)-1,$c->launcher));}};
    };
    $cases['order_exact']=static function(QueueCoreRepository $r):QueueHandler{
        $inner=new OrderExactHandler(static fn():OrderSyncService=>throw new RuntimeException('deadline handler built sync'));
        return new class($inner) implements QueueHandler{public function __construct(private QueueHandler $inner){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return $this->inner->handle($j,new QueueExecutionContext($c->attemptId,microtime(true)-1,$c->launcher));}};
    };
    foreach($cases as $type=>$factory){
        $reset();$r=new QueueCoreRepository($pdo);
        $payload=$type==='order_exact'?['order_id'=>'70001']:['from'=>'2026-08-01 00:00:00','to'=>'2026-08-02 00:00:00','generation'=>0,'limit'=>20];
        $id=$r->enqueue(new QueueJob(1,1,$type,$type==='order_exact'?'order':'orders_window',$type==='order_exact'?'70001':null,'fresh_orders',0,'deadline-'.$type,'v1','test',null,$payload,[],1,null,'operational'));
        $registry=new QueueHandlerRegistry();$registry->register($type,$factory($r));$runner=new QueueRunner($r,$registry);
        for($i=0;$i<5;$i++){
            $runner->run(new QueueRunRequest('test','deadline-'.$type.'-'.$i,1,microtime(true)+10,30,[],[$type],1,null,'operational',$id));
            $pdo->prepare('UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=?')->execute([$id]);
        }
        $row=$r->job($id);$assert(($row['state']??'')==='retry_wait'&&(int)($row['attempt_count']??-1)===0,"$type deadline exhausted its failure budget");
    }
});
$scenario('known_safe_read_gets_new_physical_attempt',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'order_exact','order','90001','fresh_orders',0,'known-retry','v1','test',null,['order_id'=>'90001'],[],3,null,'operational'));$request=fn(string $worker):QueueRunRequest=>new QueueRunRequest('test',$worker,1,microtime(true)+20,30,[],['order_exact'],1,null,'operational',$id);$first=$r->claimNext($request('known-one'),['order_exact']);$a1=$r->beginAttempt($first,'test');$assert($r->physicalTransportStarted($first,$a1,'GET','/orders/90001')&&$r->responseKnown($first,$a1,500));$assert($r->finish($first,$a1,QueueResult::retry('meli_http_error',gmdate('Y-m-d H:i:s'),500)));$second=$r->claimNext($request('known-two'),['order_exact']);$a2=$r->beginAttempt($second,'test');$assert($r->physicalTransportStarted($second,$a2,'GET','/orders/90001')&&$r->responseKnown($second,$a2,200));$assert($r->finish($second,$a2,QueueResult::completed(1,1)));$row=$r->job($id);$calls=(int)$pdo->query("SELECT COALESCE(SUM(physical_http_calls),0) FROM queue_core_attempts WHERE job_id=$id")->fetchColumn();$assert(($row['state']??'')==='completed'&&$calls===2,'known safe-read retry did not create one new physical attempt');});
$scenario('known_429_500_206_are_explicit_new_attempts',function()use($pdo,$reset,$assert){foreach([429,500,206] as $status){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'order_exact','order',(string)(91000+$status),'fresh_orders',0,'known-'.$status,'v1','test',null,['order_id'=>(string)(91000+$status)],[],3,null,'operational'));$request=fn(string $worker):QueueRunRequest=>new QueueRunRequest('test',$worker,1,microtime(true)+20,30,[],['order_exact'],1,null,'operational',$id);$first=$r->claimNext($request('known-status-'.$status),['order_exact']);$attempt=$r->beginAttempt($first,'test');$assert($r->physicalTransportStarted($first,$attempt,'GET','/orders/'.(91000+$status))&&$r->responseKnown($first,$attempt,$status));$error=$status===206?'partial_remote_page':'meli_http_error';$assert($r->finish($first,$attempt,QueueResult::retry($error,gmdate('Y-m-d H:i:s'),$status)));$second=$r->claimNext($request('known-status-next-'.$status),['order_exact']);$secondAttempt=$r->beginAttempt($second,'test');$assert(($r->job($id)['dispatch_state']??'')==='NOT_DISPATCHED'&&$r->physicalTransportStarted($second,$secondAttempt,'GET','/orders/'.(91000+$status)),'known '.$status.' did not receive a new fenced attempt');}});
$scenario('uncertain_cannot_complete',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','uncertain-complete'));$claim=$r->claimNext($request('uncertain-complete'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$assert($r->physicalTransportStarted($claim,$attempt,'GET','/orders/1'));$assert($r->finish($claim,$attempt,QueueResult::completed(1,1)));$assert(($r->job($id)['state']??'')==='review','uncertain physical result was falsely completed');});
$scenario('repository_rowcount_fences_rollback_partial_transitions',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$one=$r->enqueue($job(1,'normal','row-one'));$two=$r->enqueue($job(1,'normal','row-two'));$c1=$r->claimNext($request('row-one'),['test_work']);$a1=$r->beginAttempt($c1,'test');$c2=$r->claimNext($request('row-two'),['test_work']);$a2=$r->beginAttempt($c2,'test');$assert(!$r->physicalTransportStarted($c1,$a2,'GET','/orders/1')&&($r->job($one)['dispatch_state']??'')==='NOT_DISPATCHED','physical rowcount mismatch did not roll back');$assert($r->physicalTransportStarted($c1,$a1,'GET','/orders/1'));$assert(!$r->responseKnown($c1,$a2,200)&&($r->job($one)['dispatch_state']??'')==='DISPATCHED_RESULT_UNCERTAIN','response rowcount mismatch did not roll back');$assert(!$r->finish($c2,$a1,QueueResult::completed())&&($r->job($two)['state']??'')==='running','finish rowcount mismatch did not roll back');});
$scenario('dead_transient_revival_same_fifo_identity',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'revival','version-1','test',null,[],[],1,null,'operational'));$pdo->prepare("UPDATE queue_core_jobs SET state='dead',attempt_count=1,last_error_class='deadline',updated_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 61 SECOND) WHERE id=?")->execute([$id]);$assert($r->reviveExhaustedTransient($id,'fresh_orders_discovery','version-1'));$assert(!$r->reviveExhaustedTransient($id,'fresh_orders_discovery','version-1'));$row=$r->job($id);$assert((int)$row['id']===$id&&($row['state']??'')==='pending'&&(int)$row['attempt_count']===0&&(int)$row['revival_count']===1&&(int)$row['lease_generation']===1,'transient revival changed identity or was not atomic');});
$scenario('bad_row_does_not_block',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$make=fn(string $key):QueueJob=>new QueueJob(1,1,'manual_exact','fixture',$key,'normal',0,$key,'v1','test',null,['key'=>$key],[],3);$bad=$r->enqueue($make('bad'));$good=$r->enqueue($make('good'));$registry=new QueueHandlerRegistry();$registry->register('manual_exact',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return ($j->payload['key']??'')==='bad'?QueueResult::dead('poison'):QueueResult::completed(1);}});$s=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','worker',2,microtime(true)+20));$assert(($r->job($bad)['state']??'')==='dead'&&($r->job($good)['state']??'')==='completed'&&$s['claimed']===2);});
$scenario('manual_cron_domain_isolation',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','1','normal',0,'manual-domain','v1','test',null,[],[],3,null,'manual'));$manual=$r->claimNext(new QueueRunRequest('manual','manual',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$id),['manual_exact']);$cron=$r->claimNext(new QueueRunRequest('cron_v4','cron',1,microtime(true)+10),['manual_exact']);$assert($manual?->id===$id&&$cron===null);});
$scenario('automation_stop_zero_side_effects',function()use($pdo,$assert){$root=dirname(__DIR__);$marker=$root.'/PAUSE_ERP_AUTOMATION';file_put_contents($marker,'test');$before=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();try{$result=(new CronV4Cli())->run(['cron_v4.php','--runtime=5']);}finally{@unlink($marker);}$after=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$assert(($result['status']??'')==='SKIPPED_AUTOMATION_STOPPED'&&($result['side_effects']??-1)===0&&$before===$after);});
$scenario('ml_write_disabled_preserved',function()use($assert){putenv('ML_WRITE_ENABLED=false');$assert(getenv('ML_WRITE_ENABLED')==='false');});
$scenario('deadline_stops_claims',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$r->enqueue($job(1,'normal','deadline'));$registry=new QueueHandlerRegistry();$registry->register('test_work',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::completed();}});$s=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','w',10,microtime(true)-1));$assert($s['claimed']===0&&$s['reason']==='deadline');});
$scenario('uncertain_result_not_retried',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','uncertain'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$assert($r->dispatchStarted($c,$a,'GET','/orders/1'));$r->finish($c,$a,QueueResult::retry('transport'));$assert(($r->job($id)['state']??'')==='review');});
$scenario('producer_checkpoint_overlap',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$producer=new FreshOrdersProducer($pdo,$r,300,3600);$producer->scheduleDueAccounts();$row=$pdo->query("SELECT window_from,window_to,generation FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$from=is_array($row)?strtotime((string)$row['window_from'].' UTC'):false;$assert(is_array($row)&&$from!==false&&$from<=time()-3500);$gateway=new class implements FreshOrdersGateway{public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{return ['orders'=>[['id'=>'90001','date_created'=>$f,'input_version'=>'stable']], 'next_cursor'=>null,'has_more'=>false];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$r,$gateway));$runner=new QueueRunner($r,$registry);$runner->run(new QueueRunRequest('test','producer-one',1,microtime(true)+20,30,[],['fresh_orders_discovery'],1));$pdo->exec("UPDATE queue_core_producer_checkpoints SET next_due_at=UTC_TIMESTAMP(3) WHERE producer_key='fresh_orders' AND meli_account_id=1");$producer->scheduleDueAccounts();$runner->run(new QueueRunRequest('test','producer-two',1,microtime(true)+20,30,[],['fresh_orders_discovery'],1));$count=(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='order_exact' AND meli_account_id=1 AND resource_id='90001'")->fetchColumn();$assert($count===1,'overlap produced a duplicate order job');});
$scenario('producer_downtime_catchup',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pdo->exec("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,watermark_at,next_due_at,generation) VALUES('fresh_orders',1,1,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 2 DAY),UTC_TIMESTAMP(3),7)");(new FreshOrdersProducer($pdo,$r,300,3600))->scheduleDueAccounts();$raw=$pdo->query("SELECT payload_json FROM queue_core_jobs WHERE meli_account_id=1 AND work_type='fresh_orders_discovery' LIMIT 1")->fetchColumn();$payload=is_string($raw)?json_decode($raw,true):null;$from=is_array($payload)&&isset($payload['from'])?strtotime((string)$payload['from'].' UTC'):false;$assert($from!==false&&$from<=time()-2*86400-250,'downtime window was not materialized');});
$scenario('fresh_producer_continuous_without_reordering',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$old=$r->enqueue($job(1,'historical_backfill','old'));$producer=new FreshOrdersProducer($pdo,$r,300,3600);$result=$producer->scheduleDueAccounts(1);$claim=$r->claimNext($request('w'),['test_work','fresh_orders_discovery']);$assert($result['enqueued']===1&&$claim?->id===$old,'fresh producer must run without jumping FIFO');});
$scenario('metrics_count_useful_progress_only',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'local','noop'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::completed(0));$first=(new QueueMetricsService($pdo))->snapshot();$id2=$r->enqueue($job(1,'local','useful'));$c2=$r->claimNext($request('w2'),['test_work']);$a2=$r->beginAttempt($c2,'test');$r->finish($c2,$a2,QueueResult::completed(1));$second=(new QueueMetricsService($pdo))->snapshot();$assert($first['resources_persisted']===0&&$second['resources_persisted']===1&&$second['last_useful_progress_at']!==null);});

$scenario('fifo_retry_reentry',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'normal','retry-a'));$b=$r->enqueue($job(1,'normal','retry-b'));$claim=$r->claimNext($request('retry-1'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$r->finish($claim,$attempt,QueueResult::retry('later',gmdate('Y-m-d H:i:s',time()+3600)));$assert($r->claimNext($request('retry-2'),['test_work'])?->id===$b);$pdo->prepare("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3) WHERE id=?")->execute([$a]);$claimB=$r->job($b);$pdo->prepare("UPDATE queue_core_jobs SET state='completed',lease_owner=NULL,lease_expires_at=NULL WHERE id=?")->execute([$b]);$assert($r->claimNext($request('retry-3'),['test_work'])?->id===$a);});
$scenario('historical_ingestion_bounded',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$jobs=(function(){for($i=0;$i<500;$i++)yield new QueueJob(1,1,'test_work','history',(string)$i,'historical_backfill',0,'hist-'.$i,'v1','fixture',null,[],[],3,null,'operational');})();$blocked=false;try{(new HistoricalIngestionService())->ingest($r,$jobs,500);}catch(RuntimeException){$blocked=true;}$jobs=(function(){for($i=0;$i<500;$i++)yield new QueueJob(1,1,'test_work','history',(string)$i,'historical_backfill',0,'hist-'.$i,'v1','fixture',null,[],[],3,null,'operational');})();$count=(new HistoricalIngestionService())->ingest($r,$jobs,500,true);$assert($blocked&&$count===HistoricalIngestionService::MAX_PER_CYCLE&&(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn()===$count);});
$scenario('transport_heartbeat_prevents_reclaim',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','heartbeat'));$claim=$r->claimNext($request('heartbeat-owner'),['test_work']);$r->beginAttempt($claim,'test');$pdo->prepare("UPDATE queue_core_jobs SET lease_expires_at=DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=?")->execute([$id]);$assert($r->heartbeat($claim,5));sleep(2);$recovered=$r->recoverStale();$assert(array_sum($recovered)===0&&($r->job($id)['state']??'')==='running','active heartbeat was reclaimed');});
$scenario('stale_heartbeat_rejected',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','heartbeat-stale'));$claim=$r->claimNext($request('heartbeat-old'),['test_work']);$r->beginAttempt($claim,'test');$pdo->prepare('UPDATE queue_core_jobs SET lease_generation=lease_generation+1 WHERE id=?')->execute([$id]);$assert(!$r->heartbeat($claim,30));});
$scenario('lost_transport_fence_becomes_review',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','lost-fence'));$claim=$r->claimNext($request('lost-owner'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$assert($r->physicalTransportStarted($claim,$attempt,'GET','/orders/1'));$pdo->prepare("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=?")->execute([$id]);$recovered=$r->recoverStale();$assert($recovered['review']===1&&($r->job($id)['state']??'')==='review'&&$r->claimNext($request('no-retry'),['test_work'])===null);});
$scenario('manual_global_lease_and_heartbeat',function()use($pdo,$reset,$assert){$reset();$service=new QueueExecutionLeaseService($pdo);$manual=$service->acquire('manual','manual-owner',5);$assert($manual!==null&&$service->heartbeat($manual)&&$service->acquire('manual','second-manual',5)===null);$pdo->exec("UPDATE queue_core_execution_leases SET expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE lease_key='global'");$cron=$service->acquire('cron_v4','cron-owner',5);$assert($cron!==null&&$cron->generation>$manual->generation);});
$scenario('cron_skips_manual_without_side_effects',function()use($pdo,$reset,$assert){$reset();putenv('CRON_V4_ENABLED=true');putenv('ML_WRITE_ENABLED=false');$service=new QueueExecutionLeaseService($pdo);$manual=$service->acquire('manual','manual-active',30);$before=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$result=(new CronV4Cli($pdo))->run(['cron_v4.php','--runtime=5']);$after=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$assert(($result['status']??'')==='SKIPPED_MANUAL_ACTIVE'&&($result['side_effects']??-1)===0&&($result['producer_calls']??-1)===0&&($result['stale_recovery']??-1)===0&&$before===$after);$service->release($manual);});
$scenario('manual_allowed_automation_cron_forbidden',function()use($pdo,$reset,$assert){$reset();$root=dirname(__DIR__);$automationMarker=$root.'/PAUSE_ERP_AUTOMATION';$apiMarker=$root.'/PAUSE_MELI_API';$savedApi=is_file($apiMarker)?file_get_contents($apiMarker):null;@unlink($apiMarker);putenv('APP_KEY=queue-core-fake-transport-key');$encrypted=Crypto::encrypt('fake-access-token');$pdo->prepare("INSERT INTO meli_tokens(meli_account_id,access_token_encrypted,expires_at,refresh_version) VALUES(?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 6 HOUR),1)")->execute([1,$encrypted]);$pdo->exec("INSERT INTO app_settings(setting_key,setting_value,is_encrypted,setting_group) VALUES('api.guard.enabled','0',0,'api') ON DUPLICATE KEY UPDATE setting_value='0',is_encrypted=0");AppSettingsService::clearCache();$r=new QueueCoreRepository($pdo);$contract=['method'=>'GET','endpoint_pattern'=>'~^/orders/[0-9]+$~','operation_key'=>'order_exact','max_remote_calls'=>1];$manualId=$r->enqueue(new QueueJob(1,1,'manual_exact','fixture','1','normal',0,'manual-stop','v1','test',null,['remote_contract'=>$contract],[],3,null,'manual'));$cronId=$r->enqueue(new QueueJob(1,1,'order_exact','order','2','fresh_orders',0,'cron-stop','v1','test',null,[],[],3,null,'operational'));$transport=new class implements MeliHttpTransportInterface{public int $calls=0;public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,(string)(parse_url($url,PHP_URL_PATH)?:'/'));App\QueueCore\QueueCoreDispatchFence::transportStarted($method,(string)(parse_url($url,PHP_URL_PATH)?:'/'));$this->calls++;return ['status'=>200,'body'=>['id'=>'123'],'headers'=>[],'curl_error'=>'','duration_ms'=>1,'wire_bytes'=>2,'decoded_bytes'=>2];}};$client=new MeliApiClient(1,$transport);$handler=new class($client) implements QueueHandler{public function __construct(private MeliApiClient $client){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{$this->client->get('/orders/123',[],['job_type'=>'manual_exact']);return QueueResult::completed(1,1);}};$registry=new QueueHandlerRegistry();$registry->register('manual_exact',$handler);$registry->register('order_exact',$handler);file_put_contents($automationMarker,'test');try{$manual=(new QueueRunner($r,$registry))->run(new QueueRunRequest('manual','manual-stop',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$manualId));$cron=(new QueueRunner($r,$registry))->run(new QueueRunRequest('cron_v4','cron-stop',1,microtime(true)+10,30,[],['order_exact'],1,null,'operational',$cronId));}finally{@unlink($automationMarker);if(is_string($savedApi))file_put_contents($apiMarker,$savedApi);else @unlink($apiMarker);}$assert($manual['completed']===1&&$transport->calls===1&&$cron['claimed']===0&&$cron['reason']==='automation_stopped','manual fake GET or Cron Automation Stop contract failed');});
$scenario('waiting_oauth_resumes_same_job',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO meli_tokens(meli_account_id,access_token_encrypted,expires_at,refresh_version) VALUES(1,'x',DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 HOUR),4)");$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'oauth-wait','v1','test',null,[],[],3));$registry=new QueueHandlerRegistry();$handler=new class implements QueueHandler{public int $calls=0;public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{$this->calls++;if($this->calls===1)throw new OAuthRefreshRequiredException($j->meliAccountId);return QueueResult::completed(1);}};$registry->register('fresh_orders_discovery',$handler);$runner=new QueueRunner($r,$registry);$first=$runner->run(new QueueRunRequest('test','oauth-one',1,microtime(true)+10));$assert(($r->job($id)['state']??'')==='waiting_oauth'&&$handler->calls===1);$busy=$runner->run(new QueueRunRequest('test','oauth-busy',1,microtime(true)+10));$assert($busy['claimed']===0);$pdo->exec("UPDATE meli_tokens SET refresh_version=5,expires_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 6 HOUR) WHERE meli_account_id=1");$second=$runner->run(new QueueRunRequest('test','oauth-two',1,microtime(true)+10));$assert($second['completed']===1&&$handler->calls===2&&($r->job($id)['state']??'')==='completed');});
$scenario('producer_due_before_limit',function()use($pdo,$reset,$assert){$reset();$insert=$pdo->prepare("INSERT INTO meli_accounts(id,company_id,meli_user_id,account_name,status) VALUES(?,?,?,?, 'conectado') ON DUPLICATE KEY UPDATE company_id=VALUES(company_id),meli_user_id=VALUES(meli_user_id),account_name=VALUES(account_name),status=VALUES(status)");for($i=1;$i<=30;$i++)$insert->execute([$i,(int)ceil($i/10),(string)(1000+$i),'A'.$i]);$cp=$pdo->prepare("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,next_due_at,generation) VALUES('fresh_orders',?,?,DATE_ADD(UTC_TIMESTAMP(3),INTERVAL ? SECOND),0)");for($i=1;$i<=30;$i++)$cp->execute([(int)ceil($i/10),$i,$i===25?-1:3600]);$result=(new FreshOrdersProducer($pdo,new QueueCoreRepository($pdo),300,3600))->scheduleDueAccounts(1);$account=(int)$pdo->query("SELECT meli_account_id FROM queue_core_jobs WHERE work_type='fresh_orders_discovery' LIMIT 1")->fetchColumn();$assert($result['enqueued']===1&&$account===25);});
$scenario('fresh_empty_account_requires_explicit_bootstrap',function()use($pdo,$reset,$assert){$reset();$pdo->exec('DELETE FROM meli_orders');$result=(new FreshOrdersProducer($pdo,new QueueCoreRepository($pdo)))->scheduleDueAccounts(1);$cp=$pdo->query("SELECT last_error_class,window_from FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$assert($result['enqueued']===0&&$result['bootstrap_required']===1&&($cp['last_error_class']??'')==='bootstrap_required'&&$cp['window_from']===null&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='fresh_orders_discovery'")->fetchColumn()===0,'empty account silently bootstrapped a lookback');});
$scenario('manual_input_version_transition',function()use($pdo,$reset,$assert){$reset();$state=new CampaignItemState(true,false,true,true,'order_exact','Order','Ready',1,1,'ready');$v1=ManualInputVersion::derive(['source_id'=>'1','status'=>'pending'],$state);$same=ManualInputVersion::derive(['status'=>'pending','source_id'=>'1'],$state);$v2=ManualInputVersion::derive(['source_id'=>'1','status'=>'changed'],$state);$r=new QueueCoreRepository($pdo);$job=fn(string $version):QueueJob=>new QueueJob(1,1,'manual_exact','orders','1','normal',0,'manual:1',$version,'test',null,[],[],3);$a=$r->enqueue($job($v1));$b=$r->enqueue($job($same));$c=$r->enqueue($job($v2));$assert($v1===$same&&$v1!==$v2&&$a===$b&&$c!==$a&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='manual_exact'")->fetchColumn()===2);});
$scenario('capability_gate_rejects_uncertified',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'uncertified_remote','remote','1','normal',0,'uncertified','v1','test',null,[],[],3));$registry=new QueueHandlerRegistry();$registry->register('uncertified_remote',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::completed();}});$summary=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','capability',1,microtime(true)+10));$assert($summary['claimed']===0&&($r->job($id)['state']??'')==='pending');});
$scenario('pre_remote_fence_zero_physical',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','pre-remote'));$claim=$r->claimNext($request('pre-remote-owner'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$rhythm=new ApiRhythmPolicyService();$budget=new ApiBudgetService();$permit=$rhythm->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery','source_work_id'=>(string)$id]);$reservation=$budget->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery','source_work_id'=>(string)$id]);$assert($rhythm->dispatched($permit),'rhythm dispatch reservation failed');$pdo->prepare('UPDATE queue_core_jobs SET lease_generation=lease_generation+1 WHERE id=?')->execute([$id]);$denied=false;try{if(!$r->validateTransport($claim))throw new QueueCorePreRemoteBlockedException('denied');}catch(QueueCorePreRemoteBlockedException){$denied=true;$budget->releaseReservation($reservation);$rhythm->cancelBeforeTransport($permit);}$physical=(int)$pdo->query("SELECT physical_http_calls FROM queue_core_attempts WHERE id=$attempt")->fetchColumn();$budgetConsumed=(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn();$rhythmConsumed=(int)$pdo->query("SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states")->fetchColumn();$permitRow=$pdo->query("SELECT status,dispatched_at FROM api_remote_permits ORDER BY id DESC LIMIT 1")->fetch();$assert($denied&&$physical===0&&$budgetConsumed===0&&$rhythmConsumed===0&&($permitRow['status']??'')==='released'&&($permitRow['dispatched_at']??null)===null&&($r->job($id)['dispatch_state']??'')==='NOT_DISPATCHED','pre-remote rejection consumed a real budget/rhythm permit');});
$scenario('pre_remote_automation_race_refund',function()use($pdo,$reset,$assert){$reset();$marker=dirname(__DIR__).'/PAUSE_ERP_AUTOMATION';$rhythm=new ApiRhythmPolicyService();$budget=new ApiBudgetService();$permit=$rhythm->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);$reservation=$budget->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);try{file_put_contents($marker,'test');if((new App\Services\EmergencyControlService())->automationStopped()){throw new QueueCorePreRemoteBlockedException('automation race');}}catch(QueueCorePreRemoteBlockedException){$budget->releaseReservation($reservation);$rhythm->cancelBeforeTransport($permit);}finally{@unlink($marker);}$assert((int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states')->fetchColumn()===0&&(int)$pdo->query("SELECT COUNT(*) FROM api_remote_permits WHERE status<>'released'")->fetchColumn()===0,'Automation Stop race consumed a pre-HTTP permit');});
$scenario('pre_remote_owner_stale_refund',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','owner-stale'));$claim=$r->claimNext($request('owner-before'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$rhythm=new ApiRhythmPolicyService();$budget=new ApiBudgetService();$permit=$rhythm->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);$reservation=$budget->reserve(1,'GET','/orders/search',['source'=>'queue_core','launcher'=>'cron_v4','job_type'=>'fresh_orders_discovery']);$assert($rhythm->dispatched($permit));$pdo->prepare("UPDATE queue_core_jobs SET lease_owner='owner-after' WHERE id=?")->execute([$id]);if(!$r->validateTransport($claim)){$budget->releaseReservation($reservation);$rhythm->cancelBeforeTransport($permit);}$assert((int)$pdo->query("SELECT physical_http_calls FROM queue_core_attempts WHERE id=$attempt")->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states')->fetchColumn()===0,'stale owner consumed a pre-HTTP permit');});
$scenario('queue_core_transport_rejection_before_physical_is_not_uncertain',function()use($pdo,$reset,$assert,$enableFakeApi){
    $reset();$enableFakeApi();
    $transport=new class implements MeliHttpTransportInterface{public int $calls=0;public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{$path=(string)(parse_url($url,PHP_URL_PATH)?:'/');App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,$path);throw new RuntimeException('curl init rejected');}};
    $r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'transport-reject','v1','test',null,[],[],3,null,'operational'));
    $registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{(new MeliApiClient($j->meliAccountId,$this->transport))->get('/orders/search',[],['job_type'=>'fresh_orders_discovery']);return QueueResult::completed();}});
    (new QueueRunner($r,$registry))->run(new QueueRunRequest('test','transport-reject',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));
    $row=$r->job($id);$assert($transport->calls===0&&($row['dispatch_state']??'')==='NOT_DISPATCHED'&&($row['state']??'')==='retry_wait'&&(int)$pdo->query("SELECT COALESCE(SUM(physical_http_calls),0) FROM queue_core_attempts WHERE job_id=$id")->fetchColumn()===0&&(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn()===0&&(int)$pdo->query("SELECT COUNT(*) FROM api_remote_permits WHERE status<>'released'")->fetchColumn()===0,'pre-physical transport rejection became uncertain or leaked permits');
});
$scenario('queue_core_final_api_and_automation_races_are_zero_http',function()use($pdo,$reset,$assert,$enableFakeApi){
    foreach(['PAUSE_MELI_API','PAUSE_ERP_AUTOMATION'] as $markerName){
        $reset();$enableFakeApi();$marker=dirname(__DIR__).'/'.$markerName;@unlink($marker);
        $transport=new class($marker) implements MeliHttpTransportInterface{public int $calls=0;public function __construct(private string $marker){}public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{$path=(string)(parse_url($url,PHP_URL_PATH)?:'/');App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,$path);App\QueueCore\QueueCoreDispatchFence::transportStarted($method,$path);file_put_contents($this->marker,'race');try{App\QueueCore\QueueCoreDispatchFence::immediatelyBeforeCurl($method,$path);$this->calls++;}finally{@unlink($this->marker);}return ['status'=>200,'body'=>[],'headers'=>[],'curl_error'=>'','duration_ms'=>1,'wire_bytes'=>2,'decoded_bytes'=>2];}};
        $r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'race-'.$markerName,'v1','test',null,[],[],1,null,'operational'));
        $registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{(new MeliApiClient($j->meliAccountId,$this->transport))->get('/orders/search',[],['job_type'=>'fresh_orders_discovery']);return QueueResult::completed();}});
        (new QueueRunner($r,$registry))->run(new QueueRunRequest('cron_v4','race-'.$markerName,1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));
        $row=$r->job($id);$budget=(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn();$rhythm=(int)$pdo->query('SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states')->fetchColumn();$active=(int)$pdo->query("SELECT COUNT(*) FROM api_remote_permits WHERE status<>'released'")->fetchColumn();$assert($transport->calls===0&&($row['dispatch_state']??'')==='NOT_DISPATCHED'&&($row['state']??'')==='retry_wait'&&(int)($row['attempt_count']??-1)===0&&$budget===0&&$rhythm===0&&$active===0,$markerName.' race crossed HTTP or leaked a permit '.json_encode(['calls'=>$transport->calls,'dispatch'=>$row['dispatch_state']??null,'state'=>$row['state']??null,'attempts'=>$row['attempt_count']??null,'budget'=>$budget,'rhythm'=>$rhythm,'active'=>$active,'error'=>$row['last_error_class']??null]));
    }
});
$scenario('metrics_windows_truthful',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'local','metrics-noop'));$claim=$r->claimNext($request('metrics'),['test_work']);$attempt=$r->beginAttempt($claim,'test');$r->finish($claim,$attempt,QueueResult::completed(0));$reservedId=$r->enqueue($job(1,'normal','metrics-reserved'));$reserved=$r->claimNext($request('metrics-reserved'),['test_work']);$reservedAttempt=$r->beginAttempt($reserved,'test');$assert($reserved?->id===$reservedId&&$r->reserveTransport($reserved,$reservedAttempt));$snapshot=(new QueueMetricsService($pdo))->snapshot();$assert(isset($snapshot['window_60m'],$snapshot['current_depth'],$snapshot['cumulative'])&&$snapshot['window_60m']['dispatch_reserved']===1&&$snapshot['window_60m']['physical_http_started']===0&&$snapshot['window_60m']['completed_jobs']===1&&$snapshot['window_60m']['resources_persisted']===0&&$snapshot['last_resource_persisted_at']===null&&$snapshot['last_source_closed_at']!==null);});

$scenario('queue_core_no_legacy_fanout',function()use($pdo,$reset,$assert,$enableFakeApi,$fakeTransport){$reset();$enableFakeApi();$transport=$fakeTransport(static fn(string $method,string $path,array $data):array=>['id'=>'70001','date_created'=>'2026-08-01T10:00:00Z','last_updated'=>'2026-08-01T10:01:00Z','status'=>'paid','total_amount'=>100,'paid_amount'=>100,'currency_id'=>'COP','pack_id'=>'80001','shipping'=>['id'=>'90001'],'order_items'=>[['item'=>['id'=>'MCO123','title'=>'Producto'],'quantity'=>1,'unit_price'=>100]],'payments'=>[['id'=>'60001','status'=>'approved','transaction_amount'=>100,'date_approved'=>'2026-08-01T10:02:00Z']]]);$repository=new QueueCoreRepository($pdo);$id=$repository->enqueue(new QueueJob(1,1,'order_exact','order','70001','fresh_orders',0,'order:70001','v1','test',null,['order_id'=>'70001'],[],3,null,'operational'));$registry=new QueueHandlerRegistry();$registry->register('order_exact',new OrderExactHandler(static fn(int $account):OrderSyncService=>new OrderSyncService($account,new MeliApiClient($account,$transport))));$summary=(new QueueRunner($repository,$registry))->run(new QueueRunRequest('test','no-fanout',1,microtime(true)+20,30,[],['order_exact'],1,null,'operational',$id));$legacy=0;foreach(['cron_v3_work','system_work_queue','sale_financial_reconciliation_jobs','order_resource_enrichment_jobs'] as $table)$legacy+=(int)$pdo->query("SELECT COUNT(*) FROM `$table`")->fetchColumn();$assert($summary['completed']===1&&$transport->calls===1&&(int)$pdo->query("SELECT COUNT(*) FROM meli_orders WHERE meli_account_id=1 AND external_order_id='70001'")->fetchColumn()===1&&$legacy===0&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_pending_capabilities WHERE meli_account_id=1")->fetchColumn()===2,'Queue Core order persistence escaped its authority');});

$scenario('eight_day_gap_recovery',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO meli_orders(meli_account_id,external_order_id,date_created,status,synced_at) VALUES(1,'old-gap',DATE_SUB(UTC_TIMESTAMP(),INTERVAL 8 DAY),'paid',UTC_TIMESTAMP())");$repository=new QueueCoreRepository($pdo);$producer=new FreshOrdersProducer($pdo,$repository,300,86400,86400);$windows=[];$gateway=new class($windows) implements FreshOrdersGateway{public array $windows=[];public function __construct(array &$windows){$this->windows=&$windows;}public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{$this->windows[]=[$f,$t];return ['orders'=>[],'next_cursor'=>null,'has_more'=>false,'http_status'=>200,'response_count_state'=>'complete','paging_offset'=>(int)($cursor??0),'paging_total'=>0,'received_count'=>0];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$repository,$gateway));$runner=new QueueRunner($repository,$registry);for($i=0;$i<12;$i++){$producer->scheduleDueAccounts(100);$runner->run(new QueueRunRequest('test','gap-'.$i,1,microtime(true)+20,30,[],['fresh_orders_discovery'],1,null,'operational'));$cp=$pdo->query("SELECT watermark_at FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetchColumn();if(is_string($cp)&&(strtotime($cp.' UTC')?:0)>=time()-60)break;}$assert(count($gateway->windows)>=8,'bounded windows did not recover the eight-day gap: '.count($gateway->windows));$first=strtotime($gateway->windows[0][0].' UTC')?:PHP_INT_MAX;$latest=(int)$pdo->query("SELECT UNIX_TIMESTAMP(MAX(date_created)) FROM meli_orders WHERE meli_account_id=1")->fetchColumn();$noGap=true;for($i=1;$i<count($gateway->windows);$i++){$previousTo=strtotime($gateway->windows[$i-1][1].' UTC')?:0;$currentFrom=strtotime($gateway->windows[$i][0].' UTC')?:PHP_INT_MAX;if($currentFrom>$previousTo)$noGap=false;}$lastTo=strtotime($gateway->windows[array_key_last($gateway->windows)][1].' UTC')?:0;$assert($first<=$latest-300&&$noGap&&$lastTo>=time()-60,'gap details first='.($first-$latest).' noGap='.($noGap?'yes':'no').' lastAge='.(time()-$lastTo).' windows='.count($gateway->windows));});

$scenario('manual_fifo_order_and_target_no_bypass',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$make=fn(string $key):QueueJob=>new QueueJob(1,1,'manual_exact','manual',$key,'normal',999,$key,'v1','test',null,[],[],3,null,'manual');$a=$r->enqueue($make('A'));$b=$r->enqueue($make('B'));$blocked=$r->claimNext(new QueueRunRequest('manual','target-b',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$b),['manual_exact']);$first=$r->claimNext(new QueueRunRequest('manual','target-a',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$a),['manual_exact']);$assert($blocked===null&&$first?->id===$a&&($r->job($b)['state']??'')==='pending','manual target bypassed the FIFO head');});

$scenario('manual_fifo_order',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$ids=[];foreach(['A','B','C'] as $key)$ids[]=$r->enqueue(new QueueJob(1,1,'manual_exact','manual',$key,'normal',0,'manual-'.$key,'v1','test',null,[],[],3,null,'manual'));$seen=[];foreach($ids as $expected){$claim=$r->claimNext(new QueueRunRequest('manual','manual-'.$expected,1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$expected),['manual_exact']);$seen[]=$claim?->id;$attempt=$r->beginAttempt($claim,'manual');$r->finish($claim,$attempt,QueueResult::completed());}$assert($seen===$ids);});
$scenario('manual_abandon_closes_without_background_continuation',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','abandon','local',0,'manual-abandon','v1','manual_web',null,[],[],1,null,'manual'));$claim=$r->claimNext(new QueueRunRequest('manual','manual-abandon',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$id),['manual_exact']);$attempt=$r->beginAttempt($claim,'manual');$assert($r->abandonManualJob($id,'manual_launcher_failed'));$row=$r->job($id);$attemptRow=$pdo->query("SELECT outcome,finished_at FROM queue_core_attempts WHERE id=$attempt")->fetch();$assert(($row['state']??'')==='review'&&($row['lease_owner']??null)===null&&($attemptRow['outcome']??'')==='review'&&($attemptRow['finished_at']??null)!==null&&$r->claimNext(new QueueRunRequest('cron_v4','no-manual',1,microtime(true)+10),['manual_exact'])===null,'manual job remained active after launcher failure');});
$scenario('manual_pending_head_blocks_new_click_without_persisting_target',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$old=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','old','local',0,'manual-old','v1','manual_web',null,[],[],1,null,'manual'));$blocked=false;try{(new ManualQueueLauncher())->runExact(1,1,'orders_sync','7',false,'orders_search',str_repeat('a',64),str_repeat('b',64),str_repeat('c',64));}catch(App\QueueCore\ManualFifoBusyException $e){$blocked=str_starts_with($e->getMessage(),App\QueueCore\ManualFifoBusyException::REASON);}$assert($blocked&&$r->recoverAbandonedManualJobs()===0&&($r->job($old)['state']??'')==='pending'&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE queue_domain='manual'")->fetchColumn()===1,'new click bypassed or rewrote a live FIFO head');});
$scenario('manual_explicit_attempt_reopens_terminal_without_duplicate',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$version=str_repeat('a',64);$attemptA=str_repeat('1',64);$attemptB=str_repeat('2',64);$make=static function(string $attempt)use($version):QueueJob{return new QueueJob(1,1,'manual_exact','orders_sync','7','local',0,ManualQueueLauncher::idempotencyKey(1,1,'orders_sync','7',$version,$attempt),$version,'manual_web',null,['explicit_attempt_key'=>$attempt],[],1,null,'manual');};$first=$r->enqueue($make($attemptA));$registry=new QueueHandlerRegistry();$registry->register('manual_exact',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::review('manual_fixture_review');}});(new QueueRunner($r,$registry))->run(new QueueRunRequest('manual','first-review',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$first));$second=$r->enqueue($make($attemptB));$duplicate=$r->enqueue($make($attemptB));$registry2=new QueueHandlerRegistry();$registry2->register('manual_exact',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::completed(1,1);}});(new QueueRunner($r,$registry2))->run(new QueueRunRequest('manual','second-click',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$second));$assert($first!==$second&&$second===$duplicate&&($r->job($first)['state']??'')==='review'&&($r->job($second)['state']??'')==='completed'&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE queue_domain='manual'")->fetchColumn()===2,'explicit retry did not preserve per-click dedupe');});
$scenario('manual_stale_source_second_check_zero_http',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO sync_batch_chunks(id,meli_account_id,status,sync_type,date_from,date_to,cursor_offset,processed_count,estimated_total,next_run_at) VALUES(7,1,'queued','orders','2026-08-01 00:00:00','2026-08-02 00:00:00',0,0,20,UTC_TIMESTAMP())");$adapter=(new ManualCampaignAdapterRegistry())->forQueue('orders_sync');$state=$adapter->inspect('7',1);$authority=(new ManualSourceAuthorityService())->inspect('orders_sync','7',1,1,$state);$contract=$authority->remoteContract;$attempt=str_repeat('3',64);$version=hash('sha256','manual-stale');$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'manual_exact','orders_sync','7','normal',0,ManualQueueLauncher::idempotencyKey(1,1,'orders_sync','7',$version,$attempt),$version,'manual_web',null,['queue_key'=>'orders_sync','source_id'=>'7','operation_key'=>$authority->operationKey,'source_authority_version'=>$authority->durableInputVersion,'explicit_attempt_key'=>$attempt,'remote_contract'=>$contract],[],1,null,'manual'));$registry=new QueueHandlerRegistry();$registry->register('manual_exact',new ManualExactHandler(static function()use($pdo):void{$pdo->exec('DELETE FROM sync_batch_chunks WHERE id=7');}));(new QueueRunner($r,$registry))->run(new QueueRunRequest('manual','stale-source',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$id));$row=$r->job($id);$http=(int)$pdo->query("SELECT COALESCE(SUM(physical_http_calls),0) FROM queue_core_attempts WHERE job_id=$id")->fetchColumn();$assert(($row['state']??'')==='review'&&($row['last_error_class']??'')==='stale_source'&&$http===0,'source mutation crossed the second authority check '.json_encode(['state'=>$row['state']??null,'error'=>$row['last_error_class']??null,'http'=>$http]));});
$scenario('manual_next_click_recovers_only_abandoned_work',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pending=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','pending','local',0,'manual-pending','v1','manual_web',null,[],[],1,null,'manual'));$assert($r->recoverAbandonedManualJobs()===0&&($r->job($pending)['state']??'')==='pending','live pending manual work was falsely abandoned');$pdo->prepare("UPDATE queue_core_jobs SET state='review',last_error_class='fixture_closed',completed_at=UTC_TIMESTAMP(3) WHERE id=?")->execute([$pending]);$live=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','live','normal',0,'manual-live','v1','manual_web',null,['remote_contract'=>['method'=>'GET','max_remote_calls'=>1]],[],1,null,'manual'));$claim=$r->claimNext(new QueueRunRequest('manual','manual-live',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$live),['manual_exact']);$attempt=$r->beginAttempt($claim,'manual');$assert($r->recoverAbandonedManualJobs()===0&&($r->job($live)['state']??'')==='running','live manual work was reclaimed');$assert($r->physicalTransportStarted($claim,$attempt,'GET','/orders/1'));$pdo->prepare('UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=?')->execute([$live]);$assert($r->recoverAbandonedManualJobs()===1);$row=$r->job($live);$assert(($row['state']??'')==='review'&&($row['last_error_class']??'')==='remote_result_uncertain','expired uncertain manual work was not isolated for review');});

$scenario('cron_never_claims_manual_retry',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','retry','normal',0,'manual-retry','v1','test',null,[],[],3,null,'manual'));$pdo->prepare("UPDATE queue_core_jobs SET state='retry_wait',next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=?")->execute([$id]);$claim=$r->claimNext(new QueueRunRequest('cron_v4','cron',1,microtime(true)+10),['manual_exact']);$assert($claim===null&&($r->job($id)['state']??'')==='retry_wait');});

$scenario('partial_206_no_checkpoint',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pdo->exec("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,window_from,window_to,next_due_at,generation) VALUES('fresh_orders',1,1,'2026-08-01 00:00:00','2026-08-02 00:00:00',UTC_TIMESTAMP(3),0)");$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'partial','0','test',null,['from'=>'2026-08-01 00:00:00','to'=>'2026-08-02 00:00:00','cursor'=>null,'generation'=>0,'limit'=>20],[],3,null,'operational'));$gateway=new class implements FreshOrdersGateway{public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{return ['orders'=>[['id'=>'10101','date_created'=>$f]],'next_cursor'=>'1','has_more'=>true,'http_status'=>206,'response_count_state'=>'partial','paging_offset'=>0,'paging_total'=>2,'received_count'=>1];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$r,$gateway));(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','partial',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));$cp=$pdo->query("SELECT generation,cursor_value,watermark_at FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$children=(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='order_exact'")->fetchColumn();$assert(($r->job($id)['state']??'')==='retry_wait'&&(int)$cp['generation']===0&&$cp['cursor_value']===null&&$cp['watermark_at']===null&&$children===0);});

$scenario('short_page_no_offset_skip',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pdo->exec("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,window_from,window_to,next_due_at,generation) VALUES('fresh_orders',1,1,'2026-08-01 00:00:00','2026-08-02 00:00:00',UTC_TIMESTAMP(3),0)");$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'short','0','test',null,['from'=>'2026-08-01 00:00:00','to'=>'2026-08-02 00:00:00','cursor'=>null,'generation'=>0,'limit'=>20],[],3,null,'operational'));$gateway=new class implements FreshOrdersGateway{public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{return ['orders'=>[['id'=>'20202','date_created'=>$f]],'next_cursor'=>'1','has_more'=>true,'http_status'=>200,'response_count_state'=>'complete','paging_offset'=>0,'paging_total'=>3,'received_count'=>1];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$r,$gateway));(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','short',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));$cursor=$pdo->query("SELECT cursor_value FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetchColumn();$assert((string)$cursor==='1','short page cursor='.var_export($cursor,true));});

$scenario('complete_last_page_advances_watermark_once',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pdo->exec("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,window_from,window_to,next_due_at,generation) VALUES('fresh_orders',1,1,'2026-08-01 00:00:00','2026-08-02 00:00:00',UTC_TIMESTAMP(3),4)");$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'last-page','4','test',null,['from'=>'2026-08-01 00:00:00','to'=>'2026-08-02 00:00:00','cursor'=>'2','generation'=>4,'limit'=>20],[],3,null,'operational'));$gateway=new class implements FreshOrdersGateway{public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{return ['orders'=>[['id'=>'30303','date_created'=>$f]],'next_cursor'=>null,'has_more'=>false,'http_status'=>200,'response_count_state'=>'complete','paging_offset'=>2,'paging_total'=>3,'received_count'=>1];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$r,$gateway));$runner=new QueueRunner($r,$registry);$runner->run(new QueueRunRequest('test','last-one',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));$before=$pdo->query("SELECT watermark_at,generation FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$runner->run(new QueueRunRequest('test','last-two',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));$after=$pdo->query("SELECT watermark_at,generation FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$assert((string)$before['watermark_at']==='2026-08-02 00:00:00.000' || str_starts_with((string)$before['watermark_at'],'2026-08-02 00:00:00'));$assert((int)$before['generation']===5&&$after===$before);});

$scenario('transport_capability_endpoint_mismatch',function()use($pdo,$reset,$assert,$enableFakeApi,$fakeTransport){$reset();$enableFakeApi();$transport=$fakeTransport(static fn():array=>['results'=>[],'paging'=>['offset'=>0,'total'=>0]]);$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'wrong-endpoint','v1','test',null,[],[],3,null,'operational'));$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{(new MeliApiClient($j->meliAccountId,$this->transport))->get('/items/MCO123',[],['job_type'=>'fresh_orders_discovery']);return QueueResult::completed();}});(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','mismatch',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));$assert($transport->calls===0&&(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn()===0,'endpoint mismatch crossed transport or consumed budget');});

$scenario('order_exact_search_endpoint_mismatch',function()use($pdo,$reset,$assert,$enableFakeApi,$fakeTransport){$reset();$enableFakeApi();$transport=$fakeTransport(static fn():array=>['results'=>[],'paging'=>['offset'=>0,'total'=>0]]);$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'order_exact','order','40404','fresh_orders',0,'wrong-order','v1','test',null,['order_id'=>'40404'],[],3,null,'operational'));$registry=new QueueHandlerRegistry();$registry->register('order_exact',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{(new MeliApiClient($j->meliAccountId,$this->transport))->get('/orders/search',[],['job_type'=>'order_exact']);return QueueResult::completed();}});(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','order-mismatch',1,microtime(true)+10,30,[],['order_exact'],1,null,'operational',$id));$assert($transport->calls===0);});

$scenario('uncertified_manual_endpoint_zero_http',function()use($pdo,$reset,$assert,$enableFakeApi,$fakeTransport){$reset();$enableFakeApi();$transport=$fakeTransport(static fn():array=>['id'=>'1']);$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'manual_exact','manual','1','normal',0,'manual-uncertified','v1','test',null,['queue_key'=>'module_jobs','source_id'=>'1'],[],3,null,'manual'));$registry=new QueueHandlerRegistry();$registry->register('manual_exact',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{(new MeliApiClient($j->meliAccountId,$this->transport))->get('/items/MCO123',[],['job_type'=>'manual_exact']);return QueueResult::completed();}});(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','manual-uncertified',1,microtime(true)+10,30,[],['manual_exact'],1,null,'manual',$id));$assert($transport->calls===0);});

$scenario('second_http_blocked_and_valid_endpoint_allowed',function()use($pdo,$reset,$assert,$enableFakeApi,$fakeTransport){$reset();$enableFakeApi();$transport=$fakeTransport(static fn():array=>['results'=>[],'paging'=>['offset'=>0,'total'=>0]]);$r=new QueueCoreRepository($pdo);$id=$r->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'one-call','v1','test',null,[],[],3,null,'operational'));$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{$api=new MeliApiClient($j->meliAccountId,$this->transport);$api->get('/orders/search',[],['job_type'=>'fresh_orders_discovery']);$api->get('/orders/search',[],['job_type'=>'fresh_orders_discovery']);return QueueResult::completed();}});(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','one-call',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id));$budgetRows=(int)$pdo->query('SELECT COUNT(*) FROM api_budget_windows')->fetchColumn();$badBudget=(int)$pdo->query('SELECT COUNT(*) FROM api_budget_windows WHERE request_count<>1')->fetchColumn();$activePermits=(int)$pdo->query("SELECT COUNT(*) FROM api_remote_permits WHERE status IN ('reserved','dispatched')")->fetchColumn();$rhythmCalls=(int)$pdo->query("SELECT COALESCE(calls_in_block,0) FROM api_rhythm_states WHERE scope_key='global'")->fetchColumn();$retry=$r->claimNext(new QueueRunRequest('test','no-blind-retry',1,microtime(true)+10,30,[],['fresh_orders_discovery'],1,null,'operational',$id),['fresh_orders_discovery']);$assert($transport->calls===1&&(int)$pdo->query("SELECT physical_http_calls FROM queue_core_attempts WHERE job_id=$id")->fetchColumn()===1&&($r->job($id)['state']??'')==='review'&&$retry===null&&$budgetRows>0&&$badBudget===0&&$activePermits===0&&$rhythmCalls===1&&(int)$pdo->query('SELECT COUNT(*) FROM queue_core_producer_checkpoints')->fetchColumn()===0,'valid first endpoint, second-call fence, source closure, or refund state failed');});

$scenario('manual_input_version_volatile_fields_ignored',function()use($reset,$assert){$reset();$one=new CampaignItemState(true,false,true,true,'order_exact','Label A','Mensaje A',1,1,'ready','2026-08-08 10:00:00');$two=new CampaignItemState(true,false,true,true,'order_exact','Label B','Mensaje B',1,1,'ready','2026-08-09 10:00:00');$source=['queue_key'=>'orders_sync','source_id'=>'7','status'=>'pending','message'=>'old','next_eligible_at'=>'x'];$changedPresentation=$source;$changedPresentation['message']='new';$changedPresentation['next_eligible_at']='y';$sameA=ManualInputVersion::derive($source,$one);$sameB=ManualInputVersion::derive($changedPresentation,$two);$changed=$source;$changed['status']='completed';$different=ManualInputVersion::derive($changed,$two);$assert($sameA===$sameB&&$different!==$sameA);});

$scenario('manual_input_version_from_source_authority',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO sync_batch_chunks(id,meli_account_id,status,sync_type,date_from,date_to,cursor_offset,processed_count,estimated_total,next_run_at) VALUES(7,1,'queued','orders','2026-08-01 00:00:00','2026-08-02 00:00:00',0,0,20,'2026-08-08 10:00:00')");$state=new CampaignItemState(true,false,true,true,'orders_search','Ordenes','Ready',1,1,'ready','2026-08-08 10:00:00');$service=new ManualSourceAuthorityService();$a=$service->inspect('orders_sync','7',1,1,$state);$previewA=['queue_key'=>'orders_sync','source_id'=>'7','meli_account_id'=>1,'message'=>'A','nextEligibleAt'=>'2026-08-08 10:00:00'];$versionA=ManualInputVersion::deriveFromSourceAuthority($previewA,$a);$pdo->exec("UPDATE sync_batch_chunks SET next_run_at='2026-08-09 12:00:00' WHERE id=7");$same=$service->inspect('orders_sync','7',1,1,$state);$previewB=$previewA;$previewB['message']='B';$previewB['nextEligibleAt']='2026-08-09 12:00:00';$versionSame=ManualInputVersion::deriveFromSourceAuthority($previewB,$same);$pdo->exec("UPDATE sync_batch_chunks SET cursor_offset=20,processed_count=20 WHERE id=7");$b=$service->inspect('orders_sync','7',1,1,$state);$versionB=ManualInputVersion::deriveFromSourceAuthority($previewB,$b);$repo=new QueueCoreRepository($pdo);$make=fn(string $version):QueueJob=>new QueueJob(1,1,'manual_exact','orders_sync','7','normal',0,'manual-orders-7',$version,'test',null,[],[],3,null,'manual');$jobA=$repo->enqueue($make($versionA));$jobSame=$repo->enqueue($make($versionSame));$jobB=$repo->enqueue($make($versionB));$assert($a->remoteContract!==null&&$versionA===$versionSame&&$versionB!==$versionA&&$jobA===$jobSame&&$jobB!==$jobA,'manual durable source authority did not preserve logical versions');});

$scenario('manual_capability_sales_audit',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO sync_sales_audit_runs(id,meli_account_id,status) VALUES(90,1,'running')");$pdo->exec("INSERT INTO sync_sales_audit_jobs(id,status,sync_sales_audit_run_id,next_offset,remote_reported_total,page_limit) VALUES(11,'pending',90,0,100,20)");$state=new CampaignItemState(true,false,true,true,'sales_audit','Auditoria','Ready',1,1,'ready');$authority=(new ManualSourceAuthorityService())->inspect('sales_audit','11',1,1,$state);$contract=$authority->remoteContract;$physical=(new MeliOperationProfileRegistry())->resolve('GET','/orders/search',['job_type'=>'sales_audit']);$assert(!$authority->explicitlyUnsupported&&$authority->operationKey==='sales_audit'&&($contract['method']??'')==='GET'&&($contract['endpoint_pattern']??'')==='~^/orders/search$~'&&($contract['operation_key']??'')==='orders_search'&&($physical['key']??'')===($contract['operation_key']??'')&&($contract['max_remote_calls']??0)===1);});

$scenario('manual_capability_module_job_explicitly_unsupported',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO system_module_jobs(id,meli_account_id,module_id,job_type,status,stage,progress_current,progress_total,payload_json,checkpoint_json) VALUES(12,1,'meli-insights','insights_refresh','pending','reputation',0,4,'{}','{}')");$adapter=(new ManualCampaignAdapterRegistry())->forQueue('module_jobs');$state=new CampaignItemState(true,false,true,true,'insights','Modulo','Ready',1,1,'ready');$authority=(new ManualSourceAuthorityService())->inspect('module_jobs','12',1,1,$state);$assert($adapter!==null&&!$adapter->supportsExact()&&$authority->explicitlyUnsupported&&$authority->remoteContract===null,'module job was advertised without an exact source-bound endpoint');});

$scenario('manual_enrichment_shipment',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO order_resource_enrichment_jobs(id,meli_account_id,meli_order_id,resource_type,external_resource_id,status) VALUES(21,1,1001,'shipment','70001','pending')");$state=new CampaignItemState(true,false,true,true,'shipment_exact','Envio','Ready',1,1,'ready');$authority=(new ManualSourceAuthorityService())->inspect('order_enrichment','21',1,1,$state);$assert($authority->operationKey==='shipment_exact'&&($authority->remoteContract['endpoint_pattern']??'')==='~^/shipments/[0-9]+$~'&&($authority->remoteContract['max_remote_calls']??0)===1);});

$scenario('manual_enrichment_pack',function()use($pdo,$reset,$assert){$reset();$pdo->exec("INSERT INTO order_resource_enrichment_jobs(id,meli_account_id,meli_order_id,resource_type,external_resource_id,status) VALUES(22,1,1002,'pack','80001','pending')");$state=new CampaignItemState(true,false,true,true,'shipment_exact','Pack','Ready',1,1,'ready');$authority=(new ManualSourceAuthorityService())->inspect('order_enrichment','22',1,1,$state);$assert($authority->operationKey==='pack_exact'&&($authority->remoteContract['endpoint_pattern']??'')==='~^/packs/[0-9]+$~'&&($authority->remoteContract['max_remote_calls']??0)===1);});

$scenario('manual_all_exact_adapters_have_contract_or_unsupported',function()use($reset,$assert){$reset();$adapters=(new ManualCampaignAdapterRegistry())->all();$registry=new ManualRemoteCapabilityRegistry();$certified=0;$unsupported=0;foreach($adapters as $adapter){if(!$adapter->supportsExact()){if($adapter->queueKey()==='module_jobs')$unsupported++;continue;}$operation=match($adapter->queueKey()){'notification_fallback','sales_repair'=>'order_exact','orders_sync'=>'orders_search','items_sync'=>'item_detail','catalog_descriptions'=>'item_description','financial_recalc'=>'local_financial','sales_audit'=>'sales_audit','order_enrichment'=>'shipment_exact','sale_pack_reconciliation'=>'pack_exact','sale_financial_reconciliation'=>'billing_orders',default=>''};if($operation==='local_financial'){$certified++;continue;}$contract=$registry->forOperation($operation);$assert($contract!==null&&($contract['max_remote_calls']??0)===1,'missing exact adapter contract: '.$adapter->queueKey());$certified++;}$assert($certified===10&&$unsupported===1,'manual capability matrix drifted certified='.$certified.' unsupported='.$unsupported);});
$scenario('manual_registry_reports_full_capability_universe',function()use($reset,$assert){$reset();$health=(new ManualCampaignAdapterRegistry())->health();$certified=$health['exact_certified']??[];$unsupported=$health['explicitly_unsupported']??[];$gaps=$health['eligible_without_source_bound_capability']??[];$assert(count($certified)===10&&count($unsupported)===5&&$gaps===[],'manual registry did not classify its real universe');foreach($health['adapters']??[] as $queue=>$row)$assert(in_array($row['status']??'', ['exact_certified','explicitly_unsupported','eligible_without_source_bound_capability'],true),'adapter missing explicit category: '.$queue);});

$scenario('known_http_policy_is_bounded',function()use($pdo,$reset,$assert,$enableFakeApi){
    $expected=[401=>'review',403=>'review',404=>'completed',429=>'retry_wait',500=>'retry_wait',206=>'retry_wait'];
    foreach($expected as $status=>$state){
        $reset();$enableFakeApi();
        $transport=new class($status) implements MeliHttpTransportInterface{public int $calls=0;public function __construct(private int $status){}public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{$path=(string)(parse_url($url,PHP_URL_PATH)?:'/');App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,$path);App\QueueCore\QueueCoreDispatchFence::transportStarted($method,$path);App\QueueCore\QueueCoreDispatchFence::immediatelyBeforeCurl($method,$path);$this->calls++;return ['status'=>$this->status,'body'=>[],'headers'=>[],'curl_error'=>'','duration_ms'=>1,'wire_bytes'=>2,'decoded_bytes'=>2];}};
        $repository=new QueueCoreRepository($pdo);$id=$repository->enqueue(new QueueJob(1,1,'order_exact','order','1','fresh_orders',0,'policy-'.$status,'v1','test',null,['order_id'=>'1'],[],3,null,'operational'));
        $handlers=new QueueHandlerRegistry();$handlers->register('order_exact',new class($transport) implements QueueHandler{public function __construct(private MeliHttpTransportInterface $transport){}public function handle(QueueClaim $job,QueueExecutionContext $context):QueueResult{(new MeliApiClient($job->meliAccountId,$this->transport))->get('/orders/1',[],['job_type'=>'order_exact']);return QueueResult::completed(1,1);}});
        (new QueueRunner($repository,$handlers))->run(new QueueRunRequest('test','policy-'.$status,1,microtime(true)+10,30,[],['order_exact'],1,null,'operational',$id));
        $row=$repository->job($id);$assert($transport->calls===1&&($row['state']??'')===$state,'HTTP '.$status.' policy state='.($row['state']??'missing'));
    }
});

$scenario('final_deadline_fence_refunds_without_http',function()use($pdo,$reset,$assert,$enableFakeApi){
    $reset();$enableFakeApi();
    $transport=new class implements MeliHttpTransportInterface{
        public int $calls=0;
        public function request(string $method,string $url,array $data,array $headers,bool $form,array $timeouts):array{
            $path=(string)(parse_url($url,PHP_URL_PATH)?:'/');
            App\QueueCore\QueueCoreDispatchFence::beforeTransport($method,$path);
            App\QueueCore\QueueCoreDispatchFence::transportStarted($method,$path);
            usleep(2200000);
            App\QueueCore\QueueCoreDispatchFence::immediatelyBeforeCurl($method,$path);
            $this->calls++;
            return ['status'=>200,'body'=>[],'headers'=>[],'curl_error'=>'','duration_ms'=>1,'wire_bytes'=>2,'decoded_bytes'=>2];
        }
    };
    $repository=new QueueCoreRepository($pdo);
    $id=$repository->enqueue(new QueueJob(1,1,'fresh_orders_discovery','orders_window',null,'fresh_orders',0,'deadline-final','v1','test',null,[],[],3,null,'operational'));
    $handlers=new QueueHandlerRegistry();
    $handlers->register('fresh_orders_discovery',new class($transport) implements QueueHandler{
        public function __construct(private MeliHttpTransportInterface $transport){}
        public function handle(QueueClaim $job,QueueExecutionContext $context):QueueResult{
            (new MeliApiClient($job->meliAccountId,$this->transport))->get('/orders/search',[],['job_type'=>'fresh_orders_discovery']);
            return QueueResult::completed();
        }
    });
    CronDeadlineContext::start(5,3,2,1);
    try{
        (new QueueRunner($repository,$handlers))->run(new QueueRunRequest('test','deadline-final',1,microtime(true)+5,30,[],['fresh_orders_discovery'],1,null,'operational',$id));
    }finally{CronDeadlineContext::clear();}
    $row=$repository->job($id);
    $physical=(int)$pdo->query("SELECT COALESCE(SUM(physical_http_calls),0) FROM queue_core_attempts WHERE job_id=$id")->fetchColumn();
    $budget=(int)$pdo->query('SELECT COALESCE(SUM(request_count),0) FROM api_budget_windows')->fetchColumn();
    $rhythm=(int)$pdo->query('SELECT COALESCE(SUM(calls_in_block),0) FROM api_rhythm_states')->fetchColumn();
    $active=(int)$pdo->query("SELECT COUNT(*) FROM api_remote_permits WHERE status<>'released'")->fetchColumn();
    $assert($transport->calls===0&&$physical===0&&($row['dispatch_state']??'')==='NOT_DISPATCHED'&&($row['state']??'')==='retry_wait'&&(int)($row['attempt_count']??-1)===0&&($row['last_error_class']??'')==='deadline'&&$budget===0&&$rhythm===0&&$active===0,'final deadline crossed cURL or leaked permits '.json_encode(['calls'=>$transport->calls,'physical'=>$physical,'dispatch'=>$row['dispatch_state']??null,'state'=>$row['state']??null,'attempts'=>$row['attempt_count']??null,'error'=>$row['last_error_class']??null,'budget'=>$budget,'rhythm'=>$rhythm,'active'=>$active]));
});

$passed=count(array_filter($results));$total=count($results);echo "QUEUE_CORE_TESTS=$passed/$total\n";exit($passed===$total?0:1);
