<?php
declare(strict_types=1);

$root=dirname(__DIR__);require $root.'/bootstrap.php';
use App\Core\Database;
use App\QueueCore\FreshOrdersDiscoveryHandler;
use App\QueueCore\FreshOrdersGateway;
use App\QueueCore\FreshOrdersProducer;
use App\QueueCore\QueueClaim;
use App\QueueCore\QueueCoreRepository;
use App\QueueCore\QueueExecutionContext;
use App\QueueCore\QueueHandler;
use App\QueueCore\QueueHandlerRegistry;
use App\QueueCore\QueueJob;
use App\QueueCore\QueueMetricsService;
use App\QueueCore\QueueResult;
use App\QueueCore\QueueRetryPolicy;
use App\QueueCore\QueueRunner;
use App\QueueCore\QueueRunRequest;
use App\QueueCore\CronV4Cli;

$dsn=getenv('QUEUE_CORE_TEST_DSN')?:'';$user=getenv('QUEUE_CORE_TEST_USER')?:'';$pass=getenv('QUEUE_CORE_TEST_PASS')?:'';
if($dsn===''){fwrite(STDERR,"QUEUE_CORE_TEST_DSN is required\n");exit(2);} $pdo=new PDO($dsn,$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);$pdo->exec("SET time_zone='+00:00'");Database::setConnection($pdo);
$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['queue_core_dispatch_journal','queue_core_attempts','queue_core_events','queue_core_jobs','queue_core_producer_checkpoints','queue_core_scheduler_state','queue_core_account_fairness','meli_accounts'] as $t){$pdo->exec("DROP TABLE IF EXISTS `$t`");}$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
$pdo->exec("CREATE TABLE meli_accounts (id BIGINT UNSIGNED NOT NULL PRIMARY KEY,company_id BIGINT UNSIGNED NOT NULL,meli_user_id VARCHAR(80) NULL,account_name VARCHAR(100) NULL,status VARCHAR(40) NOT NULL) ENGINE=InnoDB");$pdo->exec("INSERT INTO meli_accounts VALUES (1,1,'101','A','conectado'),(2,1,'102','B','conectado'),(3,2,'201','C','conectado')");
$sql=file_get_contents($root.'/database/migrations/280_queue_core_cron_v4_phase_b1.sql');if(!is_string($sql))throw new RuntimeException('migration missing');foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql)?:[] as $statement){$statement=trim($statement);if($statement!==''&&!str_starts_with($statement,'--')){$pdo->exec($statement);}elseif(str_contains($statement,"CREATE TABLE")){$pdo->exec(preg_replace('/^--[^\n]*\n(?:--[^\n]*\n)*/','',$statement)??$statement);}}
// Idempotency of the schema itself.
foreach(preg_split('/;\s*(?:\r?\n|$)/',$sql)?:[] as $statement){$statement=trim($statement);if($statement!==''&&!str_starts_with($statement,'--')){$pdo->exec($statement);}elseif(str_contains($statement,"CREATE TABLE")){$pdo->exec(preg_replace('/^--[^\n]*\n(?:--[^\n]*\n)*/','',$statement)??$statement);}}

$results=[];$scenario=function(string $name,callable $test)use(&$results):void{try{$test();$results[$name]=true;echo "PASS $name\n";}catch(Throwable $e){$results[$name]=false;fwrite(STDERR,"FAIL $name ".$e->getMessage()."\n");}};$assert=function(bool $ok,string $message='assertion failed'):void{if(!$ok)throw new RuntimeException($message);};
$reset=function()use($pdo):void{$pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach(['queue_core_dispatch_journal','queue_core_attempts','queue_core_events','queue_core_jobs','queue_core_producer_checkpoints','queue_core_account_fairness'] as $t)$pdo->exec("TRUNCATE TABLE `$t`");$pdo->exec('SET FOREIGN_KEY_CHECKS=1');$pdo->exec("UPDATE queue_core_scheduler_state SET cycle_position=0,generation=0 WHERE scheduler_key='default'");};
$parallel=function(string $mode):array{$start=(int)floor(microtime(true)*1000)+500;$procs=[];$outputs=[];for($i=0;$i<2;$i++){$pipes=[];$proc=proc_open([PHP_BINARY,__DIR__.'/fixtures/queue_core_race_worker.php',$mode,'worker-'.$i,(string)$start],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__));if(!is_resource($proc))throw new RuntimeException('parallel worker did not start');$procs[]=[$proc,$pipes];}foreach($procs as [$proc,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($proc);if($code!==0)throw new RuntimeException('parallel worker failed: '.$err);$outputs[]=json_decode((string)$out,true,32,JSON_THROW_ON_ERROR);}return $outputs;};
$job=function(int $account,string $lane,string $key,int $max=5,int $company=1):QueueJob{return new QueueJob($company,$account,'test_work','test_resource',$key,$lane,0,$key,'v1','test',null,['key'=>$key],[],$max);};
$request=function(string $worker,int $max=1,float $deadline=0,array $ids=[]):QueueRunRequest{return new QueueRunRequest('test',$worker,$max,$deadline>0?$deadline:microtime(true)+30,30,$ids);};

$scenario('fresh_beats_30k_historical',function()use($pdo,$reset,$assert,$job,$request){$reset();$pdo->beginTransaction();$s=$pdo->prepare("INSERT INTO queue_core_jobs(company_id,meli_account_id,work_type,resource_type,resource_id,lane,idempotency_key,input_version,state,max_attempts,available_at,source,payload_json,provenance_json) VALUES(1,1,'test_work','history',?,'historical_backfill',?,'v1','pending',3,UTC_TIMESTAMP(3),'fixture','{}','{}')");for($i=1;$i<=30000;$i++)$s->execute([(string)$i,'h'.$i]);$pdo->commit();$r=new QueueCoreRepository($pdo);$fresh=$r->enqueue($job(2,'fresh_orders','fresh-b'));$claim=$r->claimNext($request('w'),['test_work']);$assert($claim?->id===$fresh,'fresh was not first');});
$scenario('historical_starvation_bounded',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$historical=$r->enqueue($job(1,'historical_backfill','old'));for($i=0;$i<20;$i++)$r->enqueue($job(2,'fresh_orders','f'.$i));$seen=0;for($i=0;$i<10;$i++){$c=$r->claimNext($request('w'.$i),['test_work']);if(!$c)break;$seen++;if($c->id===$historical)break;$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::completed());}$assert($seen<=6 && (($r->job($historical)['state']??'')==='claimed'),'historical exceeded bounded slot');});
$scenario('account_fairness',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);for($i=0;$i<50;$i++)$r->enqueue($job(1,'normal','a'.$i));$b=$r->enqueue($job(2,'normal','b'));$c1=$r->claimNext($request('w1'),['test_work']);$a=$r->beginAttempt($c1,'test');$r->finish($c1,$a,QueueResult::completed());$c2=$r->claimNext($request('w2'),['test_work']);$assert($c2?->id===$b,'second account was monopolized');});
$scenario('duplicate_producer_call',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$a=$r->enqueue($job(1,'fresh_orders','same'));$b=$r->enqueue($job(1,'fresh_orders','same'));$assert($a===$b && (int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn()===1);});
$scenario('concurrent_producer_race',function()use($pdo,$reset,$assert,$parallel){$reset();$rows=$parallel('enqueue');$assert((int)$rows[0]['id']===(int)$rows[1]['id']&&(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE idempotency_key='parallel-producer'")->fetchColumn()===1);});
$scenario('duplicate_claim_race',function()use($pdo,$reset,$assert,$job,$parallel){$reset();(new QueueCoreRepository($pdo))->enqueue($job(1,'normal','claim'));$rows=$parallel('claim');$ids=array_values(array_filter(array_map(static fn(array $r):int=>(int)($r['id']??0),$rows)));$assert(count($ids)===1,'two concurrent workers claimed the same job');});
$scenario('lease_expiry_reclaim',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','lease'));$r->claimNext($request('old'),['test_work']);$pdo->exec("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=$id");$rec=$r->recoverStale();$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=$id");$new=$r->claimNext($request('new'),['test_work']);$assert($rec['retry_wait']===1&&$new?->leaseGeneration===2);});
$scenario('stale_generation_finalize_rejected',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','stale'));$old=$r->claimNext($request('old'),['test_work']);$oldAttempt=$r->beginAttempt($old,'test');$pdo->exec("UPDATE queue_core_jobs SET lease_expires_at=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE id=$id");$r->recoverStale();$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3),available_at=UTC_TIMESTAMP(3) WHERE id=$id");$new=$r->claimNext($request('new'),['test_work']);$assert($new!==null&&!$r->finish($old,$oldAttempt,QueueResult::completed()));});
$scenario('retry_wait_eligibility',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','retry'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::retry('temporary',gmdate('Y-m-d H:i:s',time()+3600)));$assert($r->claimNext($request('x'),['test_work'])===null);$pdo->exec("UPDATE queue_core_jobs SET next_attempt_at=UTC_TIMESTAMP(3) WHERE id=$id");$assert($r->claimNext($request('y'),['test_work'])!==null);});
$scenario('retry_after_respected',function()use($assert,$root){$at=QueueRetryPolicy::nextAttemptAt(1,120);$then=new DateTimeImmutable($at,new DateTimeZone('UTC'));$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$delta=$then->getTimestamp()-$now->getTimestamp();$client=(string)file_get_contents($root.'/app/Services/MeliApiClient.php');$assert($delta>=119&&$delta<=121&&str_contains($client,'$status === 429 || $retryAfter !== null'));});
$scenario('dead_after_max_attempts',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','dead',1));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::retry('still_bad'));$assert(($r->job($id)['state']??'')==='dead');});
$scenario('bad_row_does_not_block',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$bad=$r->enqueue($job(1,'normal','bad'));$good=$r->enqueue($job(1,'normal','good'));$registry=new QueueHandlerRegistry();$registry->register('test_work',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return ($j->payload['key']??'')==='bad'?QueueResult::dead('poison'):QueueResult::completed(1);}});$s=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','worker',2,microtime(true)+20));$assert(($r->job($bad)['state']??'')==='dead'&&($r->job($good)['state']??'')==='completed'&&$s['claimed']===2);});
$scenario('manual_cron_same_claim_path',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','shared'));$manual=$r->claimNext(new QueueRunRequest('manual','manual',1,microtime(true)+10,30,[$id]),['test_work']);$cron=$r->claimNext(new QueueRunRequest('cron_v4','cron',1,microtime(true)+10),['test_work']);$assert($manual!==null&&$cron===null);});
$scenario('automation_stop_zero_side_effects',function()use($pdo,$assert){$root=dirname(__DIR__);$marker=$root.'/PAUSE_ERP_AUTOMATION';file_put_contents($marker,'test');$before=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();try{$result=(new CronV4Cli())->run(['cron_v4.php','--runtime=5']);}finally{@unlink($marker);}$after=(int)$pdo->query('SELECT COUNT(*) FROM queue_core_jobs')->fetchColumn();$assert(($result['status']??'')==='SKIPPED_AUTOMATION_STOPPED'&&($result['side_effects']??-1)===0&&$before===$after);});
$scenario('ml_write_disabled_preserved',function()use($assert){putenv('ML_WRITE_ENABLED=false');$assert(getenv('ML_WRITE_ENABLED')==='false');});
$scenario('deadline_stops_claims',function()use($pdo,$reset,$assert,$job){$reset();$r=new QueueCoreRepository($pdo);$r->enqueue($job(1,'normal','deadline'));$registry=new QueueHandlerRegistry();$registry->register('test_work',new class implements QueueHandler{public function handle(QueueClaim $j,QueueExecutionContext $c):QueueResult{return QueueResult::completed();}});$s=(new QueueRunner($r,$registry))->run(new QueueRunRequest('test','w',10,microtime(true)-1));$assert($s['claimed']===0&&$s['reason']==='deadline');});
$scenario('uncertain_result_not_retried',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'normal','uncertain'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$assert($r->dispatchStarted($c,$a,'GET','/orders/1'));$r->finish($c,$a,QueueResult::retry('transport'));$assert(($r->job($id)['state']??'')==='review');});
$scenario('producer_checkpoint_overlap',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$producer=new FreshOrdersProducer($pdo,$r,300,3600);$producer->scheduleDueAccounts();$row=$pdo->query("SELECT window_from,window_to,generation FROM queue_core_producer_checkpoints WHERE producer_key='fresh_orders' AND meli_account_id=1")->fetch();$from=is_array($row)?strtotime((string)$row['window_from'].' UTC'):false;$assert(is_array($row)&&$from!==false&&$from<=time()-3500);$gateway=new class implements FreshOrdersGateway{public function fetch(int $c,int $a,string $f,string $t,?string $cursor,int $limit):array{return ['orders'=>[['id'=>'90001','date_created'=>$f,'input_version'=>'stable']], 'next_cursor'=>null,'has_more'=>false];}};$registry=new QueueHandlerRegistry();$registry->register('fresh_orders_discovery',new FreshOrdersDiscoveryHandler($pdo,$r,$gateway));$runner=new QueueRunner($r,$registry);$runner->run(new QueueRunRequest('test','producer-one',1,microtime(true)+20,30,[],['fresh_orders_discovery'],1));$pdo->exec("UPDATE queue_core_producer_checkpoints SET next_due_at=UTC_TIMESTAMP(3) WHERE producer_key='fresh_orders' AND meli_account_id=1");$producer->scheduleDueAccounts();$runner->run(new QueueRunRequest('test','producer-two',1,microtime(true)+20,30,[],['fresh_orders_discovery'],1));$count=(int)$pdo->query("SELECT COUNT(*) FROM queue_core_jobs WHERE work_type='order_exact' AND meli_account_id=1 AND resource_id='90001'")->fetchColumn();$assert($count===1,'overlap produced a duplicate order job');});
$scenario('producer_downtime_catchup',function()use($pdo,$reset,$assert){$reset();$r=new QueueCoreRepository($pdo);$pdo->exec("INSERT INTO queue_core_producer_checkpoints(producer_key,company_id,meli_account_id,watermark_at,next_due_at,generation) VALUES('fresh_orders',1,1,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 2 DAY),UTC_TIMESTAMP(3),7)");(new FreshOrdersProducer($pdo,$r,300,3600))->scheduleDueAccounts();$raw=$pdo->query("SELECT payload_json FROM queue_core_jobs WHERE meli_account_id=1 AND work_type='fresh_orders_discovery' LIMIT 1")->fetchColumn();$payload=is_string($raw)?json_decode($raw,true):null;$from=is_array($payload)&&isset($payload['from'])?strtotime((string)$payload['from'].' UTC'):false;$assert($from!==false&&$from<=time()-2*86400-250,'downtime window was not materialized');});
$scenario('low_backlog_account_fresh_bounded',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);for($i=0;$i<1000;$i++)$r->enqueue($job(1,'normal','bulk'.$i));$b=$r->enqueue($job(2,'fresh_orders','new-b'));$claim=$r->claimNext($request('w'),['test_work']);$assert($claim?->id===$b);});
$scenario('metrics_count_useful_progress_only',function()use($pdo,$reset,$assert,$job,$request){$reset();$r=new QueueCoreRepository($pdo);$id=$r->enqueue($job(1,'local','noop'));$c=$r->claimNext($request('w'),['test_work']);$a=$r->beginAttempt($c,'test');$r->finish($c,$a,QueueResult::completed(0));$first=(new QueueMetricsService($pdo))->snapshot();$id2=$r->enqueue($job(1,'local','useful'));$c2=$r->claimNext($request('w2'),['test_work']);$a2=$r->beginAttempt($c2,'test');$r->finish($c2,$a2,QueueResult::completed(1));$second=(new QueueMetricsService($pdo))->snapshot();$assert($first['resources_persisted']===0&&$second['resources_persisted']===1&&$second['last_useful_progress_at']!==null);});

$passed=count(array_filter($results));$total=count($results);echo "QUEUE_CORE_TESTS=$passed/$total\n";exit($passed===$total&&$total===21?0:1);
