<?php
use App\Core\Auth;
use App\Core\Csrf;
use App\Core\Env;
use App\Core\View;

$base = rtrim(Env::get('APP_URL', ''), '/');
$money = static fn($v) => '$ ' . number_format((float) $v, 2, ',', '.');
?>
<div class="page-head">
  <div><a class="muted" href="<?= View::e($base) ?>/billing">← Volver a facturación</a><h1>Facturación mensual <?= View::e(substr($report['report_month'], 0, 7)) ?></h1><p><?= View::e($report['issuer_name']) ?> → <?= View::e($report['customer_name']) ?> · <?= View::e($report['account_name']) ?></p></div>
  <div class="page-actions"><a class="btn" href="<?= View::e($base) ?>/billing/export?id=<?= (int) $report['id'] ?>">Exportar CSV</a><span class="badge <?= in_array($report['status'], ['aprobado', 'facturado'], true) ? 'green' : 'amber' ?>"><?= View::e($report['status']) ?></span></div>
</div>
<section class="report-summary"><?php foreach ([['Venta bruta', $report['gross_sales']], ['Comisiones', $report['marketplace_fees']], ['Envíos', $report['shipping_costs']], ['Descuentos', $report['discounts']], ['Neto estimado', $report['estimated_net']], ['Base manual', $report['manual_base']]] as [$label, $value]): ?><div class="report-stat"><span><?= View::e($label) ?></span><strong><?= $money($value) ?></strong></div><?php endforeach; ?></section>
<?php if (in_array($report['status'], ['borrador', 'revisado'], true)): ?><section class="panel filter-bar"><form class="inline-form" method="post" action="<?= View::e($base) ?>/billing/update"><input type="hidden" name="_token" value="<?= Csrf::token() ?>"><input type="hidden" name="id" value="<?= (int) $report['id'] ?>"><div class="field"><label>Base manual final</label><input class="input" type="number" step="0.01" name="manual_base" value="<?= View::e($report['manual_base']) ?>" required></div><button class="btn primary">Guardar base</button></form></section><?php endif; ?>
<?php if (in_array(Auth::role(), ['admin', 'operador'], true)): ?><section class="panel filter-bar"><form class="inline-form" method="post" action="<?= View::e($base) ?>/billing/transition"><input type="hidden" name="_token" value="<?= Csrf::token() ?>"><input type="hidden" name="id" value="<?= (int) $report['id'] ?>"><div class="field"><label>Nuevo estado</label><select class="input" name="status"><?php $next = match ($report['status']) {'borrador' => Auth::role() === 'admin' ? ['revisado', 'anulado'] : ['revisado'], 'revisado' => Auth::role() === 'admin' ? ['borrador', 'aprobado', 'anulado'] : ['borrador'], 'aprobado' => Auth::role() === 'admin' ? ['facturado', 'anulado'] : [], default => []}; foreach ($next as $state): ?><option><?= View::e($state) ?></option><?php endforeach; ?></select></div><div class="field"><label>Referencia factura (al facturar)</label><input class="input" name="reference" value="<?= View::e($report['external_invoice_reference']) ?>"></div><?php if ($next): ?><button class="btn primary" data-confirm="Confirma el cambio de estado de la facturación.">Actualizar estado</button><?php endif; ?></form></section><?php endif; ?>
<section class="panel table-panel"><header class="panel-head"><h2>Productos consolidados</h2><span class="muted"><?= count($items) ?> SKU</span></header><div class="table-scroll"><table class="data-table"><thead><tr><th>SKU</th><th>Producto</th><th>Unidades</th><th>Venta bruta</th><th>Comisiones</th><th>Envíos</th><th>Descuentos</th><th>Neto</th><th>Base manual</th></tr></thead><tbody><?php foreach ($items as $i): ?><tr><td><strong><?= View::e($i['seller_sku']) ?></strong></td><td><?= View::e($i['product_title']) ?></td><td><?= (int) $i['units'] ?></td><td><?= $money($i['gross_sales']) ?></td><td><?= $money($i['marketplace_fees']) ?></td><td><?= $money($i['shipping_costs']) ?></td><td><?= $money($i['discounts']) ?></td><td><?= $money($i['estimated_net']) ?></td><td><?= $money($i['manual_base']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
