CREATE TABLE IF NOT EXISTS catalogs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    description TEXT NULL,
    visibility ENUM('public','private_token','private_password','internal_only') NOT NULL DEFAULT 'internal_only',
    access_token_hash CHAR(64) NULL,
    password_hash VARCHAR(255) NULL,
    is_public TINYINT(1) NOT NULL DEFAULT 0,
    is_enabled TINYINT(1) NOT NULL DEFAULT 1,
    allow_indexing TINYINT(1) NOT NULL DEFAULT 0,
    allow_public_print TINYINT(1) NOT NULL DEFAULT 0,
    allow_private_print TINYINT(1) NOT NULL DEFAULT 1,
    account_scope ENUM('all','single_account') NOT NULL DEFAULT 'all',
    meli_account_id BIGINT UNSIGNED NULL,
    category_scope ENUM('all','selected') NOT NULL DEFAULT 'all',
    selected_categories_json JSON NULL,
    public_statuses_json JSON NULL,
    include_out_of_stock TINYINT(1) NOT NULL DEFAULT 1,
    show_prices TINYINT(1) NOT NULL DEFAULT 1,
    show_stock TINYINT(1) NOT NULL DEFAULT 1,
    show_full_badge TINYINT(1) NOT NULL DEFAULT 1,
    show_sold_count TINYINT(1) NOT NULL DEFAULT 0,
    show_ratings TINYINT(1) NOT NULL DEFAULT 0,
    show_meli_link TINYINT(1) NOT NULL DEFAULT 1,
    show_internal_sku TINYINT(1) NOT NULL DEFAULT 0,
    show_status TINYINT(1) NOT NULL DEFAULT 0,
    show_created_date TINYINT(1) NOT NULL DEFAULT 0,
    show_updated_date TINYINT(1) NOT NULL DEFAULT 1,
    layout_type ENUM('ml_blue','clean_white','compact') NOT NULL DEFAULT 'ml_blue',
    expires_at DATETIME NULL,
    last_refreshed_at DATETIME NULL,
    last_refresh_status ENUM('never','updated','requires_update','updating','error','incomplete') NOT NULL DEFAULT 'never',
    last_refresh_message VARCHAR(500) NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_catalog_slug (slug),
    KEY idx_catalogs_visibility_enabled (visibility, is_enabled),
    KEY idx_catalogs_account (account_scope, meli_account_id),
    KEY idx_catalogs_created_by (created_by),
    CONSTRAINT fk_catalogs_account FOREIGN KEY (meli_account_id) REFERENCES meli_accounts(id) ON DELETE SET NULL,
    CONSTRAINT fk_catalogs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_catalogs_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    catalog_id BIGINT UNSIGNED NOT NULL,
    meli_item_id BIGINT UNSIGNED NOT NULL,
    meli_account_id BIGINT UNSIGNED NOT NULL,
    external_item_id VARCHAR(40) NOT NULL,
    external_variation_id BIGINT UNSIGNED NULL,
    title_snapshot VARCHAR(255) NOT NULL,
    sku_snapshot VARCHAR(120) NULL,
    price_snapshot DECIMAL(18,2) NOT NULL DEFAULT 0,
    price_min DECIMAL(18,2) NULL,
    price_max DECIMAL(18,2) NULL,
    currency_id VARCHAR(20) NULL,
    thumbnail_url VARCHAR(500) NULL,
    permalink VARCHAR(500) NULL,
    category_id VARCHAR(80) NULL,
    category_name VARCHAR(190) NULL,
    category_slug VARCHAR(160) NULL,
    stock_available INT NOT NULL DEFAULT 0,
    sold_quantity INT NOT NULL DEFAULT 0,
    status VARCHAR(80) NULL,
    listing_type_id VARCHAR(80) NULL,
    logistic_type VARCHAR(80) NULL,
    shipping_mode VARCHAR(80) NULL,
    is_full TINYINT(1) NOT NULL DEFAULT 0,
    full_detection_status ENUM('confirmed','not_full','unknown') NOT NULL DEFAULT 'unknown',
    has_variations TINYINT(1) NOT NULL DEFAULT 0,
    variations_count INT UNSIGNED NOT NULL DEFAULT 0,
    is_active TINYINT(1) NOT NULL DEFAULT 0,
    is_paused TINYINT(1) NOT NULL DEFAULT 0,
    is_out_of_stock TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    manual_sort_order INT NULL,
    is_visible TINYINT(1) NOT NULL DEFAULT 1,
    visibility_override ENUM('inherit','visible','hidden') NOT NULL DEFAULT 'inherit',
    hidden_by BIGINT UNSIGNED NULL,
    hidden_at DATETIME NULL,
    hidden_reason VARCHAR(255) NULL,
    source_updated_at DATETIME NULL,
    last_seen_in_source_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_catalog_item_publication (catalog_id, meli_item_id),
    UNIQUE KEY uq_catalog_item_snapshot (catalog_id, meli_item_id, external_variation_id),
    KEY idx_catalog_items_catalog_visible (catalog_id, is_visible, status),
    KEY idx_catalog_items_category (catalog_id, category_id, is_visible),
    KEY idx_catalog_items_category_slug (catalog_id, category_slug, is_visible),
    KEY idx_catalog_items_account (catalog_id, meli_account_id, is_visible),
    KEY idx_catalog_items_status (catalog_id, status, is_visible),
    KEY idx_catalog_items_stock (catalog_id, stock_available, is_visible),
    KEY idx_catalog_items_full (catalog_id, is_full, is_visible),
    KEY idx_catalog_items_price (catalog_id, price_snapshot),
    KEY idx_catalog_items_title (catalog_id, title_snapshot),
    KEY idx_catalog_items_external (catalog_id, external_item_id),
    KEY idx_catalog_items_sku (catalog_id, sku_snapshot),
    KEY idx_catalog_items_hidden_by (hidden_by),
    CONSTRAINT fk_catalog_items_catalog FOREIGN KEY (catalog_id) REFERENCES catalogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_items_item FOREIGN KEY (meli_item_id) REFERENCES meli_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_items_account FOREIGN KEY (meli_account_id) REFERENCES meli_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_items_hidden_by FOREIGN KEY (hidden_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_categories (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    catalog_id BIGINT UNSIGNED NOT NULL,
    external_category_id VARCHAR(80) NULL,
    name VARCHAR(190) NOT NULL,
    display_name VARCHAR(190) NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    slug VARCHAR(160) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    product_count INT UNSIGNED NOT NULL DEFAULT 0,
    is_visible TINYINT(1) NOT NULL DEFAULT 1,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    renamed_at DATETIME NULL,
    hidden_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_catalog_category_slug (catalog_id, slug),
    KEY idx_catalog_categories_catalog_visible (catalog_id, is_visible, sort_order),
    KEY idx_catalog_categories_external (catalog_id, external_category_id),
    KEY idx_catalog_categories_parent (parent_id),
    CONSTRAINT fk_catalog_categories_catalog FOREIGN KEY (catalog_id) REFERENCES catalogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_categories_parent FOREIGN KEY (parent_id) REFERENCES catalog_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS catalog_views (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    catalog_id BIGINT UNSIGNED NOT NULL,
    catalog_item_id BIGINT UNSIGNED NULL,
    viewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    view_day DATE NOT NULL,
    ip_hash CHAR(64) NULL,
    user_agent_hash CHAR(64) NULL,
    referrer VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_catalog_views_catalog_day (catalog_id, view_day),
    KEY idx_catalog_views_item_day (catalog_item_id, view_day),
    KEY idx_catalog_views_hash_day (catalog_id, ip_hash, user_agent_hash, view_day),
    CONSTRAINT fk_catalog_views_catalog FOREIGN KEY (catalog_id) REFERENCES catalogs(id) ON DELETE CASCADE,
    CONSTRAINT fk_catalog_views_item FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO app_settings (setting_key, setting_value, setting_group, is_encrypted)
VALUES
('catalog.tracking_enabled', '0', 'catalog', 0),
('catalog.views_retention_days', '90', 'catalog', 0),
('catalog.public_page_size', '24', 'catalog', 0),
('catalog.private_page_size', '48', 'catalog', 0)
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value), setting_group=VALUES(setting_group);

INSERT IGNORE INTO app_versions (version, notes)
VALUES ('2.8.0', 'Catalogo publico y privado de productos Mercado Libre.');
