CREATE TABLE IF NOT EXISTS manual_drain_sessions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_token CHAR(64) NOT NULL,
    owner_user_id BIGINT UNSIGNED NOT NULL,
    status_ui VARCHAR(30) NOT NULL DEFAULT 'ACQUIRING',
    drain_generation BIGINT UNSIGNED NOT NULL DEFAULT 0,
    lease_owner_hash CHAR(64) NOT NULL,
    profile_revision INT UNSIGNED NOT NULL DEFAULT 1,
    profile_snapshot_json MEDIUMTEXT NULL,
    jobs_processed INT UNSIGNED NOT NULL DEFAULT 0,
    remote_calls_observed INT UNSIGNED NOT NULL DEFAULT 0,
    burst_remote_calls_current INT UNSIGNED NOT NULL DEFAULT 0,
    last_completed_job_id BIGINT UNSIGNED NULL,
    last_result_json MEDIUMTEXT NULL,
    manual_interval_until DATETIME(3) NULL,
    manual_cooldown_until DATETIME(3) NULL,
    heartbeat_at DATETIME(3) NULL,
    expires_at DATETIME(3) NULL,
    started_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    finished_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_manual_drain_session_token (session_token),
    KEY idx_manual_drain_status_expiry (status_ui, expires_at),
    KEY idx_manual_drain_owner_created (owner_user_id, created_at),
    KEY idx_manual_drain_generation (drain_generation)
);
