<?php
use App\Core\Env;
use App\Core\View;
$base = rtrim((string) Env::get('APP_URL', ''), '/');
$items = $pageData['items'] ?? [];
$number = static fn($value): string => number_format((float) $value, 2, ',', '.');
$isZero = static fn(string $value): bool => preg_match('/^-?0(?:\.0+)?$/', $value) === 1;
$labels = ['opening'=>'Saldo inicial','receipt'=>'Entrada','sale_issue'=>'Venta ML','sale_reversal'=>'Reversión venta','adjustment_in'=>'Ajuste entrada','adjustment_out'=>'Ajuste salida','reserve'=>'Reserva','release'=>'Liberación'];
?>
<div class="page-head"><div><h1>Kardex de inventario</h1><p>Libro append-only de todas las entradas, salidas, reservas y reversiones.</p></div><div class="page-actions"><a class="btn" href="<?= View::e($base) ?>/inventory">Volver a existencias</a></div></div>
<section class="panel filter-bar"><form method="get" class="inline-form">
  <div class="field"><label for="kardex-company">Empresa</label><select class="input" id="kardex-company" name="company_id"><option value="0">Todas</option><?php foreach($companies as $company):?><option value="<?= (int)$company['id'] ?>" <?= (int)$filters['company_id']===(int)$company['id']?'selected':'' ?>><?= View::e($company['name']) ?></option><?php endforeach;?></select></div>
  <div class="field"><label for="kardex-warehouse">Bodega</label><select class="input" id="kardex-warehouse" name="warehouse_id"><option value="0">Todas</option><?php foreach($warehouses as $warehouse):?><option value="<?= (int)$warehouse['id'] ?>" <?= (int)$filters['warehouse_id']===(int)$warehouse['id']?'selected':'' ?>><?= View::e($warehouse['company_name'].' · '.$warehouse['name']) ?></option><?php endforeach;?></select></div>
  <div class="field"><label for="kardex-product">Producto</label><select class="input" id="kardex-product" name="internal_product_id"><option value="0">Todos</option><?php foreach($products as $product):?><option value="<?= (int)$product['id'] ?>" <?= (int)$filters['internal_product_id']===(int)$product['id']?'selected':'' ?>><?= View::e($product['internal_sku'].' · '.$product['name']) ?></option><?php endforeach;?></select></div>
  <div class="field"><label for="kardex-type">Tipo</label><select class="input" id="kardex-type" name="movement_type"><option value="">Todos</option><?php foreach($labels as $value=>$label):?><option value="<?= View::e($value) ?>" <?= $filters['movement_type']===$value?'selected':'' ?>><?= View::e($label) ?></option><?php endforeach;?></select></div>
  <div class="field"><label for="kardex-from">Desde</label><input class="input" id="kardex-from" type="date" name="from" value="<?= View::e($filters['from']) ?>"></div><div class="field"><label for="kardex-to">Hasta</label><input class="input" id="kardex-to" type="date" name="to" value="<?= View::e($filters['to']) ?>"></div>
  <button class="btn" type="submit">Filtrar</button>
</form></section>
<section class="panel table-panel"><header class="panel-head"><div><h2>Movimientos</h2><p><?= number_format((int)$pageData['total'],0,',','.') ?> registros inmutables.</p></div></header><div class="table-scroll"><table class="data-table" data-responsive="cards"><thead><tr><th>Fecha</th><th>Producto</th><th>Bodega</th><th>Tipo</th><th>Entrada</th><th>Salida</th><th>Reserva Δ</th><th>Costo</th><th>Saldo disponible</th><th>Referencia</th><th>Usuario / fuente</th></tr></thead><tbody><?php if(!$items):?><tr><td colspan="11"><div class="empty">No hay movimientos para estos filtros.</div></td></tr><?php endif;?><?php foreach($items as $row):?><?php $delta=(string)$row['on_hand_delta'];$zero=$isZero($delta);$negative=str_starts_with($delta,'-');?><tr><td data-label="Fecha"><?= View::e($row['created_at']) ?></td><td data-label="Producto"><strong><?= View::e($row['internal_sku']) ?></strong><br><?= View::e($row['product_name']) ?></td><td data-label="Bodega"><?= View::e($row['warehouse_name']) ?><br><span class="muted"><?= View::e($row['company_name']) ?></span></td><td data-label="Tipo"><span class="badge"><?= View::e($labels[$row['movement_type']]??$row['movement_type']) ?></span></td><td data-label="Entrada"><?= !$zero&&!$negative?$number($delta):'—' ?></td><td data-label="Salida"><?= !$zero&&$negative?$number(substr($delta,1)):'—' ?></td><td data-label="Reserva Δ"><?= $number($row['reserved_delta']) ?></td><td data-label="Costo">$ <?= $number($row['unit_cost']) ?></td><td data-label="Saldo disponible"><?= $number($row['available_after']) ?></td><td data-label="Referencia"><?= View::e($row['reference_type'].' · '.$row['reference_id']) ?></td><td data-label="Usuario / fuente"><?= View::e(($row['actor_name']?:$row['source']).($row['account_name']?' · '.$row['account_name']:'')) ?></td></tr><?php endforeach;?></tbody></table></div>
<?php if((int)$pageData['pages']>1):?><nav class="pagination" aria-label="Paginación de kardex"><?php for($page=1;$page<=$pageData['pages'];$page++):if($page>1&&$page<$pageData['page']-1||$page<$pageData['pages']&&$page>$pageData['page']+1)continue;$query=array_merge($_GET,['page'=>$page]);?><a class="btn small <?= $page===$pageData['page']?'primary':'' ?>" href="<?= View::e($base.'/inventory/kardex?'.http_build_query($query)) ?>"><?= $page ?></a><?php endfor;?></nav><?php endif;?></section>
